### ISSUE TITLE
video recording of image topics (interaction cam and head cam)

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#112]
Here is a "tested" solution:
1. `rosrun topic_tools throttle messages /head_xtion/rgb8/image_mono 1 /record/head`
2. `rosrun image_view video_recorder /image:=/record _fps:=1 /camera_info:=/head_xtion/rgb8/camera_info _codec:=fmp4 _filename:=record.avi`

The feed that should be recorded should first be annotated via #93, and the throttling should occur before the annotation.

This call shall be included in the logging launch. Good idea, @cdondrup ?

**Comment by marc-hanheide** [comment]
Oh, here's the link to the used video_recorder node: https://github.com/ros-perception/image_pipeline/blob/indigo/image_view/src/nodes/video_recorder.cpp

**Comment by cdondrup** [comment]
Closed via #138
