### ISSUE TITLE
safety measures

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#121]
- [x] `magnetic_barriers` is turned on (EBC parameters per default `laser_rear` turned on)
- [ ] put monitors in place for and call the emergency node (@jailander)
  - chest_cam publisher
  - odometry
  - laser
- [x] set up email notifications
- [x] test cliff detection (@nilsbore) and calibrate

**Comment by marc-hanheide** [comment]
The RearLaser needs to be enabled in https://github.com/strands-project/scitos_drivers/blob/indigo-devel/scitos_mira/resources/SCITOS-G5.xml#L13 surposingly (@cburbridge to confirm)

**Comment by nilsbore** [comment]
@Jailander Please monitor `/move_base/points_subsampled`, check that it's publishing at least at 2 FPS.
