### ISSUE TITLE
[bellbot] new updates and fixes - how to handle pull request?

### ISSUE THREAD

**Issue by gatsoulis** [strands-project/aaf_deployment#125]
I've updated various things both in the aaf_bellbot package and mainly in the strands_hri/bellbot_gui to fix former issues. Namely,
- No longer tries to write on where the deb packages are installed rather it uses .ros/bellbot and aaf_bellbot folders instead. The latter can also be changed to .ros/bellbot if it is deemed that aaf_deployment goes to the deb packages or there is not write access in general.
- First page has support for "locale", can have a look for the others also if it is deemed necessary.
- Tidying up.

Have tested it with a bellbot_gui launch, but not with the aaf_bellbot launch one...

How would you like to handle the updates, pull request and testing?

PS: I will have a look on the bellbot_action_server at some point as it also needs a bit of tidying up.

EDIT: changes are on my forks of strands_hri and aaf_deployment

**Comment by cdondrup** [comment]
I think it's best if you just open a PR so we can have a look and know which branch to check out.
