### ISSUE TITLE
log overall system start and stop

### ISSUE THREAD

**Issue by hawesie** [strands-project/aaf_deployment#143]
To allow us to judge how long the system runs for, please can someone add some logging to the AAF system on overall start up and shut down? For G4S this is done in the routine as follows:

``` python
        #this is in the init method:
        self._logging_msg_store = MessageStoreProxy(collection='task_events') 

        te = TaskEvent(task=None, event=TaskEvent.ROUTINE_STARTED, time=rospy.get_rostime(), description='Routine started')
        self._logging_msg_store.insert(te)
        rospy.on_shutdown(self._log_end)


    def _log_end(self):
        te = TaskEvent(task=None, event=TaskEvent.ROUTINE_STOPPED, time=rospy.get_rostime(), description='Routine stopped')
        self._logging_msg_store.insert(te)

```

**Comment by marc-hanheide** [comment]
You may want to look at https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_logging/scripts/start_stop_logging.py which is what we schedule as a task in the morning and evening respectively. Maybe we should have a chat about the "routines" at AAF and how we use GCal etc. I feel there is some confusion, and it my be useful for you guys, too.

**Comment by marc-hanheide** [comment]
Still @cdondrup do we want to add the above code to https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_logging/scripts/start_stop_logging.py ?

**Comment by cdondrup** [comment]
I don't think so. If I understand correctly, this should log when the robot starts and when it stops and not just when the day starts and ends. So actually our robot will hopefully run longer than for the few hours between the start and stop of the logging nodes. We talked about having a node to start the execution of the scheduler and to resume after an emergency. I think it should go in there. Log the start in the init and the end in the shutdown. So have something that runs indefinitely until failure. But maybe I got it wrong, in which case I can just add that to the start_stop node, yes.

**Comment by marc-hanheide** [comment]
Ah, sorry... misread this indeed. You're of course right. So, we could create a node "`routine_starter.py` or something that does all this?

**Comment by cdondrup** [comment]
For example, yes. If you want to create an issue for that node, you can assign me for now if you don't want or don't have time to do it.

**Comment by hawesie** [comment]
Yep @cdondrup is right, just at the start of the whole multi-week run :four_leaf_clover: and at the end :checkered_flag:

**Comment by hawesie** [comment]
@marc-hanheide this was the issue. I've checked the code and @cdondrup is logging the right things for the analysis scripts so no additional work is needed.
