### ISSUE TITLE
default robot screen?

### ISSUE THREAD

**Issue by hawesie** [strands-project/aaf_deployment#144]
What do you have on the robot's screen when it's not doing any particular task?

**Comment by marc-hanheide** [comment]
Nothing... currently all finished tasks leave the screen as it was. So the tasks decide the last page to be displayed. Bellbot shows a news page currently, walking group shows nothing (but it will be changed to display a farewell, right @cdondrup?). But as we have the info-terminal running when don't do anything else, it will most of the time show that, or - in other words - our robot is almost never not busy, hence will always display a task screen (despite the odd minute between tasks).

**Comment by cdondrup** [comment]
Yes, it will @marc-hanheide #145 ;)
