### ISSUE TITLE
[walking group] prolong Henry's walking group deployment

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#147]
hey @hawesie @marc-hanheide @cdondrup @TobKoer 

we just checked the dates for the deployment of the robot  and saw that we will lose one monday therapy session and one thursday therapy session due to bank holidays!

Therefore we considered if it would be possible to have the robot for guiding the walking groups in the week after the end of the official tiral (15th and 18th of june).

Than we would have 4 monday and 4 tuesday sessions covered!

Please do let me know as soon as possible so that we can proceed with our evaluation plan!

Cheers Denise

**Comment by marc-hanheide** [comment]
I wouldn't see a problem with it but @mzillich should have his say as its their robot and they might want it back to prepare for the review.
If it had been running for four weeks then it's not a problem for us to run it another, IF HdB is still happy to have it around.

**Comment by TobKoer** [comment]
Dear all,

I think there is no problem to have Henry a little longer for a balanced evaluation of the walking group (I also could imagine this to be the “care-task” reviewers might be most interested in)

Cheers,
Tobias.
