### ISSUE TITLE
[aaf_logging] Add throttling

### ISSUE THREAD

**Issue by nilsbore** [strands-project/aaf_deployment#148]
We need to add throttling of some topics, particularly the tf, when logging. We should probably have something like three different tiers of throttling. @hawesie Is there support for throttling in `mongodb_log`? I remember reading something about it but I can't find an option. The alternative is to add throttling nodes in between.

**Comment by hawesie** [comment]
No, there isn't a throttle option. You could add one though!

Or else `rosrun topic_tools throttle` for each topic to be throttled.

**Comment by nilsbore** [comment]
Yeah, I'll leave that for after the deployment =P. Let's go with separate nodes.

**Comment by marc-hanheide** [comment]
Simply throttling /tf doesn't sound like a good idea, as different nodes publish different parts if the tf tree in that topic st different rates. If you simply throttle /tf you only let through e.g. one message per second I think. Regardless where it came from. All others will be dropped and we'll likely never have a full tf tree stored. Or did I get this wrong?

**Comment by nilsbore** [comment]
Honestly I don't really know, I though that it would be the whole tree. I guess we can check the size of each individual message to see if it varies.

**Comment by lucasb-eyer** [comment]
@marc-hanheide is right with the individual parts of `tf` at different rates. In my experience, `/tf` is negligible in size, and mongodb is supposed to be good at handling tons of small writes.

**Comment by nilsbore** [comment]
See https://github.com/strands-project/aaf_deployment/pull/149 for relevant discussion.

**Comment by TobKoer** [comment]
Hi -
what's the status of Y2 log data by the way? 
I just like to remind once more that it was planned to use them for analysis this time around.

Cheers.

**Comment by marc-hanheide** [comment]
Did you not see my email sent to you yesterday?
