### ISSUE TITLE
[aaf_walking_group] Setting sound volume

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#150]
As required in #142 

Maybe @marc-hanheide or @nilsbore are best to answer this:

If I would like to set the sound volume for several components using the pygame managed player, would that be possible even after they have been started? Would that be the best way of achieving volume control during the walking group? I could just set the system volume and reset it after the group ends, which would be much easier I guess?!

**Comment by marc-hanheide** [comment]
we _could_ extend the pygame player to support this... not a big deal. Setting system volume is another alternative, I suppose... I'm a bit agnostic here.

**Comment by cdondrup** [comment]
I think there is two drawbacks to both: 
- Changing system volume always entails the possibility that it is not reset correctly and that therefore all the components executed after the group might have no sound. This would only concern the asking for help I guess?!
- Changing only the pygame volume does not allow to make it louder than the current system volume, which does not give the user full control over the sound settings.

I'm leaning towards the system volume but having the volume of pygame configurable would be a nice feature anyway.
