### ISSUE TITLE
[walking group] - demo for therapists next week

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#167]
hi @marc-hanheide @cdondrup @nilsbore @Jailander @mzillich @taketwo 

I talked to the therapists yesterday and as ther are two of them who never interacted with the robot yet we would like to shedule a demo for them next week.

The therapists are free to do so next Tuesday, 12th of may from 3:30pm.

Is that possible?

@mzillich. is wolfang to be found on github? could you also assign him to this thread?

**Comment by mzillich** [comment]
I asked Wolfgang for his githug account. @marc-hanheide, you would have to add him then.

**Comment by lobinho** [comment]
hi,
that would be fine. I'll be there.
wolfgang

**Comment by marc-hanheide** [comment]
OK, should be fine.

**Comment by denisehe** [comment]
Great!

**Comment by cdondrup** [comment]
I preparation you could print a few of these: https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_walking_group/doc/card.pdf and hand them to the therapists to try themselves.
