### ISSUE TITLE
[walking group] list of waypoint names

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#169]
dear @cdondrup @Jailander, @marc-hanheide, @TobKoer 

as promissed some names for the waypoints during walking group:

Rastplatz Ambulanz
Rastplatz Frisör
Rastplatz Kapelle
Rastplatz Teeküche

are there any more that need renaming?

**Comment by cdondrup** [comment]
Thanks, I don't think so. I'll rename them for the demo next week. Today they will have rather arbitrary names still.

**Comment by denisehe** [comment]
okay - thats fine! :-)
