### ISSUE TITLE
[bellbot] - evaluation questions

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#172]
hey @yianni - somehow I forgot to note down our final questions for the bellbot evaulation - do you have the 5 questions agian for me? 

Our old issue here on github seams to have gone!

Cheers Denise

**Comment by gatsoulis** [comment]
On 06/05/15 09:07, denisehe wrote:

> hey @yianni https://github.com/yianni - somehow I forgot to note 
> down our final questions for the bellbot evaulation - do you have the 
> 5 questions agian for me?
> 
> Our old issue here on github seams to have gone!
> 
> Cheers Denise
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/strands-project/aaf_deployment/issues/172.
> 
> Hi Denise,

See the following link:
https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_bellbot/conf/locale.ini

Not sure if a native has translated these.

Regards,
Yiannis

**Comment by marc-hanheide** [comment]
Pretty sure the answer is "no":

```
q1 = Ich bin satisfied with the service
q2 = Es ist convenient fo have a bellbot
q3 = Ich would use the bellbot again
q4 = Ich find the bellbot easy to use
q5 = Ich war happy with the speed of the robot
```

If you want to have a go at providing the right German questions here, @denisehe I'll put them on.

**Comment by denisehe** [comment]
Yes please!

**Comment by marc-hanheide** [comment]
Then please provide them 😉

**Comment by denisehe** [comment]
q1 = Ich bin mit dem Botenservice des Roboters zufrieden
q2 = Es ist praktisch einen Botenroboter zu haben
q3 = Ich würde den Botenroboter wieder benutzen
q4 = Ich fand den Botenroboter einfach zu bedienen
q5 = Ich war mit der Geschwindigkeit des Roboters zufrieden
