### ISSUE TITLE
AAF deployment

### ISSUE THREAD

**Issue by TobKoer** [strands-project/aaf_deployment#179]
@yianni, @marc-hanheide, @mzillich, @ToMadoRe @cdondrup @cburbridge @denisehe 
Dear all,

set-up phase starts Monday. Wolfgang and Thomas will arrive at AAF around 9:00.

Any special agenda?
Should we start a new hangout for communicaton - when is everyone else available?

Cheers.

**Comment by marc-hanheide** [comment]
We have our usual hangout starting at 10 your time. I suggest, we have that and start also only at 10, as we won't be available before 9 (our time).

**Comment by TobKoer** [comment]
Hi,

demos/trainings are scheduled tomorrow at 13:00 (UK time) with the receptionists
and at 14:30 (UK) for the therapists (walking group)!

So we have to plan around this.
Let us know what your plans are form a technical side, and when AAF staff is definitely needed. 
Cheers.

**Comment by TobKoer** [comment]
@yianni, @marc-hanheide, @mzillich, @ToMadoRe @cdondrup @cburbridge @denisehe 

status paint works: the good news: the painter is not in the house tomorrow! So walking group can be scheduled as planned!!
He will return either on Friday or some weekend(!) to finish his parts in the therapy area.

**Comment by hawesie** [comment]
Any chance someone at AAF could document this decorating excitement with a couple of photos? E.g. just some pictures of the area with the mat etc.
