### ISSUE TITLE
AAF routine and scheduler

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#18]
While we have a number of different functionalities implements, we need to implement a proper routine for the AAF deployment, including scheduled and on-demand task. The scheduler needs to be able to handle non-interruptible and interruptible tasks.
@denisehe should start by providing an informal description of the expected routine, describing what Henry should be doing when, including time and week days this is expected. Then we can implement the routine based on this information. The routine shall be printed on a poster for staff to check, so they get a feel for what the robot might be doing at any one time.

This involves:
- [ ] gathering information about the routine from @denisehe 
- [ ] drafting a routine based on this information (e.g. by @hawesie, @marc-hanheide, or @mudrole1)
- [ ] printing schedule once finalised (by @denisehe)
- [ ] integrating all the different aspects that require scheduled tasks (walking group, info terminal, bellbot) into a joint task manager (volunteers needed)

**Comment by denisehe** [comment]
okay I wanted to discuss this topic during todays hangouts anyway! :-)

**Comment by mudrole1** [comment]
Drafting of the routine should be straightforward, as we will have the actions for the tasks.

**Comment by marc-hanheide** [comment]
I think we should use the [Google Python API](https://developers.google.com/api-client-library/python/start/get_started) to be able to generate a routine from a Google Calendar. What does @hawesie think about this?

**Comment by hawesie** [comment]
I think it's a very cool idea, and should be easy enough to connect to what's there already, but I have zero spare capacity to implement it.

**Comment by marc-hanheide** [comment]
I'll have a quick look into in to assess the complexity.

**Comment by marc-hanheide** [comment]
It'll be pretty straight forward using the `icalendar` Python package and have it parse the exported iCal format from gcal. That also makes it more flexible, as any iCal source could be used.

**Comment by marc-hanheide** [comment]
I'll take this up.

**Comment by marc-hanheide** [comment]
see https://github.com/strands-project/strands_executive/issues/130

**Comment by denisehe** [comment]
@marc-hanheide @cdondrup - hi, ther had to be a slight change in the robot shedule as appointments for the walking group got mixed up. As I heard just now it is not only a single walking group on monday but two!!! The same time as on thrusday! 

Therefore I send a new shedule via mail!
