### ISSUE TITLE
provide a CSS for AAF

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#19]
The idea is that all interfaces used at AAF load a shared CSS file that follows the main guidelines for interfaces for the elderly (contrast, fonts, etc.)

**Comment by marc-hanheide** [comment]
This also involves refactoring/changing the existing interfaces. The CSS shall be deployed via strands_ui and based on bootstrap.

**Comment by marc-hanheide** [comment]
I assigned Yiannis as I felt he had some expertise in this, if not, suggest somebody else, please.

**Comment by gatsoulis** [comment]
I assume we are talking about a simple .css file, right? If that's the case then it's fine, I have done .css files in the past, not something really complex. Still, I would need some help from, I guess, you @marc-hanheide with the strands_ui integration and on how to test things given we have no robot and not sure when we get it back. Also from @denisehe as Denise will decide on these properties.

**Comment by marc-hanheide** [comment]
sure, you be assisted! I just want some people to have stuff on their agenda :wink:

**Comment by marc-hanheide** [comment]
I thought we should be using https://github.com/twbs/bootstrap/compare/master...strategicdata:master I will put this in a branch in our own https://github.com/strands-project/twitter_bootstrap.

**Comment by marc-hanheide** [comment]
@denisehe can you please check this: https://bootswatch.com/readable/ and let me know if you think it's a good style for our purpose. It's about colours and fonts, not about text size and specific buttons. More general, if this is deemed suitable.

**Comment by denisehe** [comment]
what is a CSS? 
do you mean suitable for our interface?

**Comment by marc-hanheide** [comment]
The CSS defines colours, fonts etc.

**Comment by denisehe** [comment]
okay meaning that you want to take color suggestions or font sice/type & button size ideas from there?

**Comment by marc-hanheide** [comment]
size is easily fixed (e.g. just by setting your zoom level a bit higher). you can compare to https://bootswatch.com/default/ and say which one you like better. Actually, I think the defaults are pretty good and we only have to modify specific elements that turn out to be not suitable. So, what Im looking for is a general :+1: from your end saying that there's nothing massively wrong with those designs.

**Comment by denisehe** [comment]
well for me its a bit difficult now as I see many aspects where there are several "solutions" proposed but that will not be of any relevanc efor our robot (e.g. dropdowns etc) 
bzw. it would be easyer to see what kind of things you want to implement where within the interface.

I just can say that everything below size "heading 3" is too small and that contrasts with yellow or light blue letters or grey is not strong enough.

best would be blue I think, so a darker blue.

arrors/pagenumbers indicating that there are also other pages should be as big and bold as possible - of cores also fitted to the acutal content.

**Comment by marc-hanheide** [comment]
I see... well, for all others @strands-project/aaf_deployment_team let's use bootstrap for all end-user facing websites, please. After doing a little research I came to the conclusion, that it's the best option and that we probably won't need a very taylored CSS. Maybe we change the colours of a few elements, but nothing substantial.

**Comment by marc-hanheide** [comment]
As I said in my previous comment. Let's stick to plain bootstrap for now. I played around with other option and actually it's not really an improvement. Maybe one or two changes would make sense, but reinventing the wheel is pointless here. So, everybody use bootstrap!
