### ISSUE TITLE
[control_ui] feature requests

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#199]
- [x] A list of scheduler events, e.g. the last 10 events of the `/task_executor/events` topic.
- [x] demand tasks: charging (with set time) 
- [ ] pause / resume scheduler
- [x] potentially html5 video stream of henry's screen
- [x] rosout logging

Please add more requests if you're missing anything.

**Comment by cdondrup** [comment]
Changing on demand tasks to regular task being scheduled now with high priority. providing a sensible max_duration so they do end at some point

**Comment by marc-hanheide** [comment]
That's in #209, but only marginally tested yet.

**Comment by marc-hanheide** [comment]
And #209 is already running on the control-pc for werner, so simply test it, please
