### ISSUE TITLE
staff interface

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#20]
We need a staff interface that members of staff at AAF at the reception and in @denisehe office will be using. Functionality envisioned includes:
- [ ] An entry page with a dashboard view showing battery level, map with current position, last voice output, currently executed task, pending tasks, contact details for strands admin to get in touch, and buttons to choose from the following sub functions
- [ ] View of the current robot's interface with the possibility to interact with it (simply displaying the same page)
- [ ] Bellbot interface (running the bellbot GUI) to schedule bellbot tasks
- [ ] Info-Terminal admin interface (using the infoterminal gui implementation)
- [ ] On-Demand Tasks:
  - Walking Group
  - Stop!  (get the robot out of the way, safe zones, is non-interruptible until "Continue!", The STOP button should also be on the main page labelled "emergency" (or the German word for it: "Notfall" or similar)
  - Maintenance (Will drive Henry into @denisehe office and then enter Stop mode): This allows charging by cable or other maintenance when needed. 
  - Continue (will let Henry continue after being in Stop or Maintenance Mode)

We might want to restrict some of these to @denisehe office, and not make it available at the reception, but we'll see.

All pages are served from the control-pc.

@yianni @cdondrup @hawesie @denisehe @mzillich to comment on this.

**Comment by marc-hanheide** [comment]
we need a volunteer to develop this top-level interface. Maybe someone from info-terminal group?

**Comment by cdondrup** [comment]
Also, uploading images, videos, and maybe music to the datacentre to be displayed and played during the walking group and via the info terminal.

Regarding the on demand tasks, do we need the walking group as one? As far as I understand this will be fixed events. But then again, as we have seen they might be combined into one or be cancelled.  So maybe having it as an on demand task is not a bad idea after all. But additionally staff should be advised how to send the robot away if the group is cancelled or moved because this will be an uniteruptable task and the robot would stand there and wait indefinitely.

**Comment by marc-hanheide** [comment]
I believe, we need a bit more than just interruptible or non-interruptible in the scheduler. Probably more something with priorities, e.g. if an on-demand with higher prio comes in, a lower on-demand task will still be interrupted. I think this is needed, to e.g. implement the "emergency" or "maintenance" behaviour. Or, alternatively (probably better), provide a dedicated means to stop the current task, whatever the robot is doing right now. Opinions, @mudrole1 or @hawesie?

**Comment by gatsoulis** [comment]
It would also be nice to have unix-like "nice/renice" in order to change 
the priorities on the fly.

Marc Hanheide wrote:

**Comment by marc-hanheide** [comment]
I think that would be too much for now. All we need is the ability to control what interrupts what.

**Comment by gatsoulis** [comment]
It was something that we discussed in Vienna, in the lines that tasks can be interruptible/non-interruptible at different times depending on which state they currently are, and hence they could change their status/priority. @hawesie is the man to give his insight though on this.

**Comment by marc-hanheide** [comment]
get @cburbridge involved :smile:

**Comment by mudrole1** [comment]
Or I am the woman to give the insight :D 
I am definitely going to add priorities to tasks, it should be fairy easy to modify existing system, as the optimization already takes into account some weights. However, you are talking about interrupting when a task with higher priority comes in.  I think we should avoid interrupting as much as we can :)

**Comment by marc-hanheide** [comment]
@cburbridge created a first file manager to upload photos etc to the system. It's available at http://lcas.lincoln.ac.uk/strands_media for test purposes. @denisehe, @yianni @cdondrup and @mzillich have a look to see if it fulfills your needs/expectiations and comment below.

Feel free to upload stuff and test out. Note this is potentially public right now, so don't put your private photos up.

**Comment by cdondrup** [comment]
Instant feedback. 
- Having to click upload after choosing the file seems redundant. Just automatic upload after choosing it would be nice. 
- I can only select single files, being able to select multiple and then automatically upload them would be great.
- I uploaded music but it doesn't show in the options for creating a music set.
- Images are autorotated to landscape

The rest looks great.

**Comment by cdondrup** [comment]
One more thing, downloading creates a file with the internal id instead of the filename. `54fd79cecd82ea7718a53014.mp4` is not a really speaking name ;)

**Comment by marc-hanheide** [comment]
Could you put this into an issue on https://github.com/strands-project/strands_ui/issues for @cburbridge ?

**Comment by marc-hanheide** [comment]
started working on the overall interface: https://github.com/strands-project/aaf_deployment/tree/indigo-devel/aaf_control_ui
