### ISSUE TITLE
[bellbot] - external events for robo-shedule

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#204]
hi @marc-hanheide @cdondrup @Jailander @TobKoer 

I have the external events for the first trial week. I will list the times of the seminars - please could you shedule the robot to be at his place already 15 minutes in advance.

18.5. - 08:30 - Seminar Quality Live - Seminarraum 1
19.5. - 08:30 - Seminar Quality Live - Seminarraum 1
19.5. - 13:00 - Konferenzraum 1
20.5. - 09:00 - Qualitätsmanagement Dialog 2015 - Seminarraum 1
21.5. - 08:30 - Hospitation - Konferenzraum 3

**Comment by marc-hanheide** [comment]
Do you want it to show info-terminal for all this?

Then, can @Jailander please translate these into waypoints for me?

**Comment by Jailander** [comment]
- Konferenzraum 1-> Konferenzraum
- Seminarraum 1 -> Feuerloescher
- Konferenzraum 3 -> WayPoint66

Seeing this need I'll try to make this more human firendly ;)

**Comment by marc-hanheide** [comment]
OK, they are all in the [schedule](https://www.google.com/calendar/embed?title=Henry%27s%20geplane%20Aufgaben&showTitle=0&showCalendars=0&showTz=0&mode=WEEK&height=600&wkst=2&hl=de&bgcolor=%23FFFFFF&src=henry.strands%40hanheide.net&color=%23B1365F&ctz=Europe%2FBerlin)
