### ISSUE TITLE
staff training

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#21]
We shall educate and empower members of staff at AAF, e.g. teach them
- how to use the admin interface
- about the implemented the robot's routine and abilities
- how to push the robot out of the way (tell them about emergency buttons) in case of emergency (talk to health and safety representation at AAF, @denisehe?)
- about the project's background and data recorded (and NOT recorded)
- how to report problems

**Comment by cdondrup** [comment]
Regarding the emergency buttons, they are not reachable with the covers on. Is the key easily accessible on werner or is the second side PC mounted like in Linda?
Can we use the virtual bumper to switch to freerun when pulling or pushing the robot?

**Comment by marc-hanheide** [comment]
good question...

**Comment by mzillich** [comment]
The key is not obstructed by the second/third PC. It is reachable as intended.

**Comment by denisehe** [comment]
yes - I think at first it is important that we from our core team knwo how things work and we can transfere this knowlege to further key persons at our site!

**Comment by marc-hanheide** [comment]
Agreed, we just need to teach a few multipliers...

**Comment by denisehe** [comment]
as many studies show, elderlies do learn best when tought by others or reading about things rather than via trial and error => we talked about teaching some elderlies/residents how to use the robot so that they can then mediate between potential users and the robot.

**Comment by marc-hanheide** [comment]
that would be great if you think that's working

**Comment by denisehe** [comment]
hey - I just spoke to the therapists - they can test Henry on the 15th of april from 1-2PM! :-)

unfortunatelly receptionists were not jet informed that the bellbot task would really be taken to action - one receptionist is on vacation at the time of the pilot trial the other therefore can not leafe his working space (and he is the one who is rather uneasy with having the robt at our site, so I think its not a good idea to come up with that issue if he is working on his own and therefore creating extra stress)

;-)

**Comment by marc-hanheide** [comment]
I see... can you say what he's uneasy about?

**Comment by denisehe** [comment]
well he is against the use of robots. he was quite rejective with all issues that come along with the robot - I guess has something to do with prejudices etc. 
We try to get him a bit more interestsd but I have the feeling with pressing his workschedule in times he is responsible for everything going on might not be the best strategy ;-)
