### ISSUE TITLE
[store_logs] parse the collections parameter correctly

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#219]
see
- https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_logging/launch/logging.launch#L21-L25
- https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_logging/scripts/store_logs_task.py#L41

Look here for doing it correctly: https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_waypoint_sounds/scripts/aaf_waypoint_player.py#L37

@cdondrup this is to fix to data upload problem. I will also add retries, in case the connection drop in between, no to fail the task immediately.

**Comment by cdondrup** [comment]
As I said on gitter, if you have a list of strings you can also call the upload once for each element. No need to have a json for that.

**Comment by marc-hanheide** [comment]
don't get it... see gitter
