### ISSUE TITLE
watchdogs and cron jobs on Henry

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#22]
In order to have a safe and reliable system, we need a few scripts (that we ran on Linda) to ported to Henry. There are:
- [ ] Battery watchdog (sending emails and shutting down as a last resort)
- [ ] Connection watchdog
- [ ] System responsiveness watchdog

I think @Jailander and @gestom are the experts. Can you please advice where to find the scripts and how to use them?

**Comment by hawesie** [comment]
This should be for all systems, not just AAF.

**Comment by marc-hanheide** [comment]
Hi, can I ask @gestom or @Jailander to upload those scripts somewhere or tell me where they are? What have we got and what is needed to put them on? Also if someone could go to https://lcas.lincoln.ac.uk/henry/ and implement and test this scripts there, that would be appreciated.

**Comment by gestom** [comment]
The battery checking scripts are part of the  strands_utils package.

**Comment by Jailander** [comment]
here to be exact https://github.com/strands-project/strands_utils/tree/hydro-devel/battery_check
