### ISSUE TITLE
network setup AAF

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#23]
A few issues still need sorting:
- [x] disconnections: The Wifi sometimes disconnects and won't reconnect. _Solution:_ Don't use network-manager but static settings or use `nmcli` to connect if not connected every minute via cron job
- [ ] routing: Currently, the control PC cannot reach the side PCs due to NAT. This needs to be sorted so we can have full connectivity between the machines. Alternatively, the control-PCs opens a vpn to the robot network.

**Comment by hawesie** [comment]
Also relevant for G4S @cburbridge

**Comment by marc-hanheide** [comment]
I put a "hack" on place on henry to re-connect whenever the connection is lost (happens very rarely, 1-2 times a day).

I added https://gist.github.com/marc-hanheide/8b79676812f8710b90bb to root's crontab (`sudo crontab -e`) on Henry, to check the connection every minute and reconnect if not connected.

**Comment by cburbridge** [comment]
When the robot looses connection do you ever have ROS communication issues beween nodes? I'm not 100% sure, but I think when bob looses network then reconnects, network manager might be temporarily screwing something for ROS. I would like to get rid of network manager, but if you think it is ok then I'll not "waste" the time...

**Comment by cburbridge** [comment]
You can see the setup routing on bob for the side PCs etc here: https://github.com/uobirlab/strands-bham/wiki/Bob-Setup

**Comment by marc-hanheide** [comment]
that's non-public...

The important thing is that we set ROS_IP, ROS_HOSTNAME, etc. fixed on all our machines and bind this to IPs that are not effected by the network_manager.
Then it seemed to work nicely. I'm still using network manager to connect to the wifi, as it's by far the most convenient way to set this up. The connection losses we observe seem to be due to being kicked out by the authentication server at AAF after some time. But I have not seen this impacting on the ROS infrastructure if the environment is probably configured. But we'll test this properly during the pre-deployment.

**Comment by marc-hanheide** [comment]
Can you still share the routing config you have publicly?

**Comment by cburbridge** [comment]
I have duplicated the page here: https://github.com/strands-project/scitos_robot/wiki/Bob%27s-Network-Configuration

**Comment by marc-hanheide** [comment]
One thing, I'm struggling with (and I wonder if it works for you). In this setup, including another computer on the wifi (in your case `ccarobot`) network into the ROS network is not working for me, as for instance `bobl` is NAT-ted and if it makes requests to a machine on the wifi network (e.g. `woody` in your example), that won't work as the request to appear to come from bob... Or do I get something wrong here?

**Comment by cburbridge** [comment]
This works ok for us, `bobl` can access `woody` and vice-versa by routing through `bob`. ROS communication works no problem: the camera running on `bobl` can be seen in rviz on `woody`.

**Comment by marc-hanheide** [comment]
OK, then I've got something wrong, even though it looks the same as yours. No worries, I'll find out. Thanks!

**Comment by hawesie** [comment]
@marc-hanheide do you execute the magic `sudo route add -net 192.168.0.0/24 dev eth0 gw bob` on the other computers? Without that we can't see bobl.

**Comment by marc-hanheide** [comment]
Sure, i do. I suspect some firewall magic at aaf to stop me there. As the setup works perfectly well at ours.
