### ISSUE TITLE
[aaf_logging] What to start

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#232]
@nilsbore we just realised we never ran you logging script. Are the changes in here still valid: https://github.com/strands-project/aaf_deployment/pull/137 ? Should we start the script?
Why is `/tf` in there. It's already done via `mongodb_log_tf` node, isn't it?

**Comment by nilsbore** [comment]
Yes, that should be valid although it's been updated since, so if you look at https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_logging/scripts/run_aaf_logger.bash there is no tf in there? The bash script is the thing to run, together with the stuff I added to your logging launch file.

**Comment by marc-hanheide** [comment]
Also, am I right this logs into the database `roslog` on mongo? And then into individual collections in that db named according to the topics? I'm asking because we only upload data from `message_store`. Can this be changed? What are the options?

**Comment by nilsbore** [comment]
Yes, that's correct

**Comment by marc-hanheide** [comment]
OK... then we need to replicate from more than one db :-( 
That's a little annoying as it means that we need to extend https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_logging/scripts/store_logs_task.py#L41 to work with several DBs. But I see there's no other way.

**Comment by marc-hanheide** [comment]
see https://github.com/strands-project/aaf_deployment/issues/233

**Comment by denisehe** [comment]
@marc-hanheide and @nilsbore @mzillich relevant for logging:

during infoterminal the robot does sometimes not turn its head/eyes/kinect towards the users (to the back)

**Comment by marc-hanheide** [comment]
@denisehe that's when the actual task had ended and the robot is preparing to do something else. It still shows the info terminal though.

**Comment by denisehe** [comment]
okay but it was standing like that for more than 10 minutes ;-)

**Comment by marc-hanheide** [comment]
then it had nothing to do for 10 minutes... Agreed not ideal
