### ISSUE TITLE
[safety] - bumper release and action time

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#234]
hi @nilsbore I just hit the robot a cuple of times ;-)

the timing fits really well! no adjustments required.

the only thing that happened was that after I hit the robots bumper its navigation failed from then onward so that interventions by wolfgang were necessary.

@marc-hanheide

**Comment by nilsbore** [comment]
@denisehe That's good to hear. So it waited some time and then it continued? Do you have any idea why it failed? It doesn't sound like it has anything to do with the bumper being pressed if it continued moving after a little while?

**Comment by denisehe** [comment]
yes, it waited and than cuntinued. :-)

hm I am not sure why the naviagion failed actually, it occured just after hitting the bumper when the robot started after its pause again.

but we could test it agian laiter on and see if the same thing occurs!
