### ISSUE TITLE
[walking_group] No pictures in aaf_walking_group_pictures photo set

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#237]
Did some one delete something in there? There were pictures before. They have to added otherwise the robot won't show any during the walking group. @denisehe did you change something?

**Comment by denisehe** [comment]
nope - I just wanted to add pictures in general and it did not work!

**Comment by denisehe** [comment]
ah @cdondrup I know why, I removed the general windows pics from the general repository!
I added our pics now.

**Comment by cdondrup** [comment]
But then you have to add them to the `aaf_walking_group_pictures` image set please.

**Comment by cdondrup** [comment]
I see you added pictures again. For the next walking group this should work then.

**Comment by denisehe** [comment]
yes sorry, I could not do anything before the file manager was not responding!
