### ISSUE TITLE
simulation of AAF

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#24]
We need a simulation environment of AAF to test everything properly. Maybe worthwhile asking the morse mailing list (or @kunzel) if we can easily turn the SLAM map into a blender model.

**Comment by kunzel** [comment]
So far we have modelled everything manually. Maybe there are some Blender tricks to do that (ie extrude a 3D shape from a 2D map). However, I am not aware of them, sorry.

**Comment by marc-hanheide** [comment]
Is it worthwhile asking on blender/Morse mailing lists?

**Comment by cburbridge** [comment]
@mudrole1, you created a script to add tables to the morse scene. Could this easily be adapted to simply fixed size boxes on every occupied pixel in a map image? Would there be an issue with the number of items in the scene with this simple approach?

**Comment by Jailander** [comment]
Hi I checked into it briefly after we talked about it in Vienna, I found nothing on doing it automatically, however, apparently it would be possible to create a 3D model automatically in other file formats like ply and import into blender, but that was only a ten minutes search on my phone so I am not sure at all about it since I'm not a blender expert.

I also think @cburbridge would be easy to implement, however that would mean creating many different objects I don't know how morse would cope with that?

**Comment by marc-hanheide** [comment]
check https://www.youtube.com/watch?v=ows2QTiMRPg and http://blenderartists.org/forum/archive/index.php/t-193092.html ?

**Comment by marc-hanheide** [comment]
I think the idea to vectorise using inkscape, then "clean it" in inkscape and then import into blender looks promising.

**Comment by marc-hanheide** [comment]
@Jailander could you provide a simulation launch file in this repo to start everything up to strands_navigation?

**Comment by Jailander** [comment]
with which environment? mht?

**Comment by marc-hanheide** [comment]
AAF of course ;-)

**Comment by Jailander** [comment]
Haha, Ok, I'll do so (as soon as I can), still watching the turtorial, but looks promising

**Comment by mudrole1** [comment]
@cburbridge if we have a list of coordinates, we can place simple box there. But I am worried about the correct dimensions of the environment (it must be correct in meters to fit model of the robot). However, I am worried about amount of objects.

Do we have a map of AAF? Or ideally, technical draw with dimensions. It depends how is it complicated, but should be fairy easy and take me 4-8h.

**Comment by cburbridge** [comment]
The dimensions are available in the YAML file associated with each map image. However, I think the method in the link @marc-hanheide sent is the way to go, so no worries, once I get a G4S map I'll have a go at it.

**Comment by Jailander** [comment]
Hi I have the map for AAF I'll test Marc Method tomorrow but it looks promising if you want to give a go I leave it in these links:

https://drive.google.com/file/d/0B2bBn3sIAgYRdEY1VlhZcG5sN3c/view?usp=sharing
https://drive.google.com/file/d/0B2bBn3sIAgYRcVhBUGFsRkNkNHM/view?usp=sharing

**Comment by Jailander** [comment]
@denisehe Do you think it would be possible to get a version of this map on a better quality (the room/office walls are very diffuse) and without annotations on it?
![y2_map](https://cloud.githubusercontent.com/assets/5035967/6348194/a68d1428-bc15-11e4-9888-d2cb5a38f16d.png)

**Comment by marc-hanheide** [comment]
why not use the robot's map?

**Comment by Jailander** [comment]
Its incomplete, in this map we can tell where the doors are not only the ones that where open whilst mapping and not completely straight (very big loops) and requires a lot of declutering (in the cafeteria) if @denisehe can get the other one it would be nice if not I will use the slam map.
![aaf](https://cloud.githubusercontent.com/assets/5035967/6348607/4de8e352-bc19-11e4-9c9e-a26e0b488c3f.png)

**Comment by marc-hanheide** [comment]
But this is the accurate metric map. I'd ignore (as in delete) all the noise.

**Comment by Jailander** [comment]
I tried it out yesterday and the blender model doesn't look very nice if you don't close all the walls and clean the noise, my plan was to use the dimensions of the metric map but using a nice map with straight walls and no noise which will allow us to create the whole building not only the bits we could map. If I could get it before I started working on it, currently I'm finishing other things too and I wanted to do that tonight or tomorrow morning latest. So if don't get it I will use what I have anyway.

**Comment by denisehe** [comment]
hey @Jailander (cool name by the way ^^) - which walls are the problems? and what do you need the rooms annotations for?

**Comment by Jailander** [comment]
no I don't need the room annotations, on the contrary, that map has too much text on it and if you have one without it would be awesome!, Also the office wall are a bit blurry when you export the pdf to image and I cant sharpen them easily because of the text ;) but if you don't have it is no Biggie I can use the SLAM map.

**Comment by denisehe** [comment]
one should be able to read - you mentioned WITHOUT annotations before ^^ I can ask but I can not promisse anything!

I will get back to you as soon as i know more!

**Comment by Jailander** [comment]
Thank you very much @denisehe !!!!

**Comment by denisehe** [comment]
hey, just for your information: i got in touch with the person in charge about the plan - he will have another look - so it might take some time. but hopefully he can provide us with a better one ;-)

**Comment by Jailander** [comment]
Thank you very much @denisehe I will start working on it now anyway but if you do get one I will make the improved version too.

**Comment by denisehe** [comment]
Hey Haime, unfortunatelly I can not provide you with another map of the building. All the plans available do have more annotations on it. 
Can you work sufficiently with the one you have got?

**Comment by Jailander** [comment]
Hi, yes @denisehe don't worry already been taken care of, I'll upload the simulations after lunch

**Comment by marc-hanheide** [comment]
This is done, I suppose
