### ISSUE TITLE
[media server] problems

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#248]
hi @marc-hanheide @cdondrup 

I checked the picture and music files - over night everything was deleted (exept music in the genral file manager) - but as I just saw now all the picutre and music sets are deleted/empty - so the ones you @cdondrup  installed for walking group that were connected to behavior etc.

what can we do?

**Comment by marc-hanheide** [comment]
we know and are working on it. It's still early here ;-)

**Comment by denisehe** [comment]
yes right, I always forget about the time-difference ^^

**Comment by cdondrup** [comment]
Recreated the info terminal image set. That should work, please test. 
One of the images is broken: IMG_6629.JPG

**Comment by TobKoer** [comment]
- I've seen a lot of rabbits and guinea-pigs.
  This looks all good now again.
