### ISSUE TITLE
[walking group] - feedback

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#255]
hello @cdondrup @marc-hanheide @hawesie @TobKoer 

I spoke to the therapists from mondays session yesterday - and although of the incident with the whealchair (what really needs fixing on some point) - they are still positive about having henry accompanying the sessions.
they explained that the monday session was very complicated partly due to the fact that the clients were very difficult that day.

In general the elderlies reacted positively to the robot, one lady made also autonomous use and clicked on the screen.

The therapists fed back that it is really funny for the elderlies to have henry play songs and show pictures.

I also observed that elderlies were singing along to Henry's tunes :-)

So fingers cross for todays session :-)

**Comment by hawesie** [comment]
Excellent feedback, thanks!

At some point would be it be possible to film the walking group and Henry? This would be great for the review talks. We wouldn’t make it publicly available.

**Comment by denisehe** [comment]
I plan to bring my camera on some point to document the procedure. I think filming would be okay in general if patients are just visible from behind (most patients do have advocates and we can not film just like that).

**Comment by mzillich** [comment]
This sounds really good!
Just in case you need it, TUW has a Sony Handycam which makes quite decent movies.

**Comment by denisehe** [comment]
@mzillich great thanks, good to know! I got myself a canon with cam functionality and would like to test it. but in case of truble I know whome to call ;-)

**Comment by cdondrup** [comment]
That's great feedback. Thank you @denisehe !
Let's hope today will be better. The speed of the robot will be slower to prevent such wheelchair incidents or at least make them less likely. Please, if possible, ask the therapists afterwards if they were still satisfied with the speed.

**Comment by denisehe** [comment]
yes fine! Okay, I will ask them and let you know - probably tomorrow as I have to leave directly after the session today!

**Comment by cdondrup** [comment]
OK, thank you.

**Comment by TobKoer** [comment]
as @denisehe mentioned: filming from behind is okay (after getting okay from therapists, which won't be a big problem I guess).
If we want to show more details and at the same time stick to code of ethics we wuld have to blur out faces, even when presenting only to reviewers.

**Comment by denisehe** [comment]
@cdondrup @marc-hanheide @hawesie @mzillich @Jailander @nilsbore 

hey you all - it was just amazing!!!!!!!!!!!!!!!
I think we can really be proud of what was accomplished since the winter school!

It was a really cool and joyful atmosphere - elderlies were interested in the robot, the pictures, the music, they sang and danced along - one lady did not even walk normally anymore but moved to the sounds :-D

really really great :-D the best robot performance I saw - EVER!!!!!!!

**Comment by mzillich** [comment]
I can tell that you are happy :)
Very cool to hear!

**Comment by hawesie** [comment]
This is amazing. 

With my coordinator hat on we need to make sure we can record this if possible, and also get the feedback/results that demonstrate this improvement. 

Excellent work all!

**Comment by denisehe** [comment]
yes we have the before during and after observation protocols, ratings from therapists ans observers from every group during the trial as well as before and after, and group discussions in the end with all participating therapists.

films: I think henry films anyway except in the waiting are

I will bring my cam once and probably also our PR department

**Comment by cdondrup** [comment]
I am very proud of henry. :) I had a smile on my face the whole time I remotely observed the group to intervene if there are errors. Really made my day seeing everyone so happy. I even saw kisses handed out to the therapists while looking at some of the pictures (which we should have on film)
Let's hope it stays that way. Thank you very much for the observations and the feedback @denisehe !

**Comment by denisehe** [comment]
yes it was really really great - I still swim in the mood of the walking group!

yes that sequence was very lovely indeed - also the dancing while waiting in the beginning!!!

and during the second group four more doors of the administration wing were opened - I assume to notice when Henry and the group pass by again :-)

yes lets hope it stays that way - let the technical stuff be with us ^^

:-D :-D :-D

**Comment by TobKoer** [comment]
By the way: feedback was also that Henry's speed is fine for therapists (I think Christian reduced it in general); so we can stick with that.

**Comment by cdondrup** [comment]
Great, thanks. The speed is just the normal movement speed of henry now and not increased any more.

**Comment by marc-hanheide** [comment]
:+1:

**Comment by denisehe** [comment]
hey @cdondrup you asked for a feedback from yesterdays session - thus, here it is:

in both groups the robot had troubles starting as it was very narrow in the corridor - I already informed the therapists to if possible not park wheelchairs near the robot so that he can drive off easily.
I helped them starting the robot, as the patients were a bit restless.

during the drive the robot mixed nature sounds and songs, which was a bit strange - as i could not see why that was.

when viewing the video nothing appeared and the picture galery was slower than last time, needing sometimes very long to load the pics (is that due to our wlan??)

3-4 times the robot had problems to continue after resting situations. then the therapists were a bit confused and unsure what to do. sometimes I helped - and luckily wolfgang came along and corresponded with marc who then intervened if the robot took all too long to recover - so thanks to @marc-hanheide and woflgang

in general the therapists seemed quite exhausted yesterday due to a heavy working day. but I overheard them saying that they consider the robot to be fun - also the older adults who were interested in the robot last time were eager to press on the screen etc.
what was also nice to see that staff came out of their office when the group was passing with the robot playing music - thus connecting the group with other people (but this might is a novelty effect).

ah and very important: is it possible to preset musik to a lower volume? when the robot starts playing along it really is very loud. ;-)

and about whealchair crashes I opened the other issue already!

**Comment by cdondrup** [comment]
Thank you for the feedback!
Regarding the sound, just change the volume on the robot in general to be a bit quieter. Then this should fix it. 
The easiest solution for the wrong button press list to just removed it I think. Has it ever been used?

**Comment by denisehe** [comment]
No it has not been used.

yes, the thing is that the volume starts always off at the highest level. e.g. after navigation falure if I remember right it starts very loud again, or after resting.
although we put it to an lower level before

**Comment by hawesie** [comment]
@denisehe if you have any pictures of such awesome performance, please upload them with the others. I'd really like to include this positive stuff at the start of the review.

**Comment by denisehe** [comment]
@hawesie  I uploaded all the material that I have in the repository marc suggested before. 
due to data policy it was not possible to really film/take pictures during the woalking group - the only material we could use there is the material from henry itself!
