### ISSUE TITLE
[walking group] - videos

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#259]
hey @marc-hanheide - could we please get the extracted video files from yesterdays WG and mondays - so that we can put it on the robot for the next WG!

thanks!

**Comment by denisehe** [comment]
@marc-hanheide hey its me again - as tomorrow is our next walking group I would need the video from last thursdays session please! 
the therapists already asked for the video!

Thanks, Denise

**Comment by marc-hanheide** [comment]
On it. Have you got software and knowledge to edit the video? It's from the whole day so needs to be cut.

**Comment by denisehe** [comment]
Ok!

No, we do not have any special software. Hm I thought that you have this fance programm where we can get any output we want ;-)

**Comment by marc-hanheide** [comment]
well... that tool is for watching annotation aligned with video, not for editing them...

**Comment by denisehe** [comment]
ok. what software is required? any special recommendations?

**Comment by cdondrup** [comment]
I'd suggest Windows Movie Maker because it should be preinstalled with every Windows distribution. Here is [a quick tutorial](http://windows.microsoft.com/en-us/windows-vista/getting-started-with-windows-movie-maker)

**Comment by cdondrup** [comment]
@marc-hanheide after @denisehe has cut the video, please make sure the encoding is correct and it plays in the html5 webplayer. I only know that h264 should work, but other formats might as well.

The video set for the walking group is already in the media server; it should be the only one here. Just upload it and add it to the set.

**Comment by marc-hanheide** [comment]
I cut it myself... It plays in owncloud (html5 player), so I hope it's alright. See email.
