### ISSUE TITLE
Scitos Node crash and video not playing

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#265]
as reported in https://github.com/strands-project/scitos_robot/issues/10#issuecomment-106298027 the scitos node crashed during the walking group. But it recovered after restarting twice. 

Also, the video of last week's group did not play apparently, although it worked fine when tested remotely. However, thinking about it, the test was in Chrome not Firefox...

**Comment by marc-hanheide** [comment]
Another scitos_node crash just now. This time the component had to be manually restarted, as it didn't crash with a segfault, but reported all the CRC errors, without killing the process

**Comment by marc-hanheide** [comment]
we need a watchdog for this at least, @cdondrup @nilsbore ?

**Comment by cdondrup** [comment]
Sounds bad. I do agree that we need a watch dog but, realistically, I can neither test nor have I much time to implement things atm.
Could we just implement a heart beat in the node and kill it when this stops? Respawn should take care of the rest.

**Comment by marc-hanheide** [comment]
@cburbridge  any ideas on this?

**Comment by cburbridge** [comment]
Adding a watchdog to the scitos node is quite easy. We could either use the ROS one (http://wiki.ros.org/watchdog_timer) or create our own. We could timeout if /odom does not get received from MIRA 5 seconds.

I prefer the option of using the ROS one, but it "does not try to reset any nodes or perform any other action. It's sole purpose is to notify that a node has failed to reset in time a watchdog"... I like it this way, we would have another node that monitors the watchdog(s) and takes action.

**Comment by cdondrup** [comment]
I would like to download the video of the group but the internet at aaf is too slow. Do we have that anywhere else, @marc-hanheide ?

**Comment by marc-hanheide** [comment]
on owncloud:
https://lcas.lincoln.ac.uk/owncloud/index.php/apps/files/?dir=%2FSTRANDS%20data%2Fdatasets%2FAAF_y2%2Fedited

On 10 June 2015 at 17:13, Christian Dondrup notifications@github.com
wrote:

> I would like to download the video of the group but the internet at aaf is
> too slow. Do we have that anywhere else, @marc-hanheide
> https://github.com/marc-hanheide ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/strands-project/aaf_deployment/issues/265#issuecomment-110816576
> .

## 

---

Dr. Marc Hanheide
Reader in Computer Science
Room MC3221B
University of Lincoln
Brayford Pool
Lincoln, LN6 7TS
Phone: +44 1522 88 6966
EMail: marc@hanheide.net
Web: http://www.hanheide.net
skype: mah99de

**Comment by cdondrup** [comment]
The video works fine for me in the walking group interface in firefox.

**Comment by marc-hanheide** [comment]
On Werner or Linda?

**Comment by cdondrup** [comment]
On my PC

**Comment by cdondrup** [comment]
Works on Linda as well.

**Comment by marc-hanheide** [comment]
Yeah, I tested that myself. That worked. But not on Werner. I installed some more codecs for Firefox but now that I think about it, I might not have restarted the browser. That could explain... Maybe a browser restart would help?

**Comment by cdondrup** [comment]
Internet is too slow to try anything... I'll try again tomorrow.
