### ISSUE TITLE
[robo crashes] what can we do??

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#267]
hey @marc-hanheide @mzillich @hawesie @TobKoer 

again it gave complaints about the robot driving into wheel chairs - three today!

I know we keep fussing about it, but it really is a problem! 

what can we do about it? christian already slowed it down - but still, the problem occurs. 

can you think of any technical solutions for that?

what can/should we do during this trial to not offend users over here or authorities who probably could stop the robots deployment due to safety risks?

I know, the robot won't crash into persons with huge impact - but with our clientel over here it is really difficult, especially as they are to slow to evade them selves or to dement to assess such situations correctly.

Best wishes
denise

**Comment by cdondrup** [comment]
You could play with the parameters for human aware navigation, but I think the main problem is that wheelchairs are not detected as people.

**Comment by hawesie** [comment]
But HAN will just slow the robot down anyway, so why not just slow it down globally?

Are the wheelchairs appearing in the costmaps? Do we need a wheelchair detector?

**Comment by denisehe** [comment]
I think @cdondrup already slowed the robot down globaly.

yes  - could something like a wheelchair detector be installed? already for this deployment?

this would really be of help!

**Comment by mzillich** [comment]
Is it that the robot does not see the wheel chairs, or parts of them?
Would it help then if the head camera would always look down to the nearest obstacle?

**Comment by marc-hanheide** [comment]
Making wheel chair detector is more of a master student's work, I.e. certainly will take months unless people like @lucasb-eyer or @mzillich have anything up in their sleeves. I wouldn't expect anything for this deployment but we can talk about it. I still would like to ask for more details:
Is this happening everywhere or particular in a specific area? Is the robot actively moving into the person (as in not seeing them at all, which would indeed be a bug and we'd need Wolfgang in a wheelchair to stress test this) or is it just e.g. turning, and slowing making contact. Are the wheelchairs stationary or were they moving as well? Were the coming from the side (blind spot) or from ahead?
@mzillich not sure I understand your idea. What would we gain from that?

**Comment by marc-hanheide** [comment]
If this happens this frequently, then, if you have not observed it yet, let's try to monitor it closely for a day or so. To finally see it happen and understand what is going on. There is no simple fix to it, so we need to really understand what the problem is. E.g. by observation or by doing test runs with wheelchairs.

**Comment by lobinho** [comment]
I could run some tests with a wheelchair today. @TobKoer could provide one. But he would need the robot to be in the lobby at 14:00 local time.

**Comment by denisehe** [comment]
hey, could you please also insert wolfgang (lobinho) to this issue - he is here and willing to test if we can get a wheelchair

well what happens is - that the robot has no sensors on its sides - therefore when a wheelchair is approaching from an sideways angle it does not detect the obstacle and goes along - this especially happens when going around corners, or when driving off from one waypoint to the other, or when continuing after the resting situation during the walking group. there the robot just navigates "blindly" to the next waypoint and when persons come along from the side it continues going along. (I told the therapists that the robot should send the robot off only if there is not much traffic in the corridor).

when wheelchairs approach from the front the robot slows down and tries to go around, but it does not see the whole shape of the person in the wheelchair and hits the legs of the person and goes by with touching either person or wheelchair which is a very akward and frightening situation for the persons. 
and also for persons close by who watch it.

it gets very difficult when there are more wheelchairs around the robot.

and the tricky thing is that we really have persons over here that are too slow to react or that can not assess the situations properly - as it is hard to predict what the robot will do next.

**Comment by lucasb-eyer** [comment]
At first, this sounded like very much like what I reported in strands-project/strands_navigation#163 and which has also been witnessed by g4s people.

From the rest of the discussion, though, I think it's more of a navigation/planning issue than a detection issue. I believe we need two different sets of parameters:
- "tight office with agile people" where it's very important the robot still moves when something's just 10cm away from it, and
- "large corridor with slow people" where it shouldn't move when there's someone/thing nearby or it doesn't know.

Also, I can only have something up my sleeve if there's enough data on the table. We might have that in my AAF recordings but that needs someone to go through and will take time. I think your suggestion of a student's thesis is a good one. But then again, this doesn't sound like a detection issue.

**Comment by mzillich** [comment]
@marc-hanheide : what I meant with the head camera looking down is just to avoid the cases when the robot does not see people coming from the side.
So if the robot would use the head camera more actively to scan for obstacles, this should get rid of those cases, right?

**Comment by marc-hanheide** [comment]
yes, if we would be using the head camera to see obstacles, which we don't at the minute, also due to limitation in what we can process.
