### ISSUE TITLE
Pre Testing Interface Solutions on Henry as long as he is still @AAF

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#27]
Dear all, 

as we have our media deployment with Henry this week - is it possible to on some point test the interfaces (just in their actual status) - this would be a good options to also give feedback, inputs etc from our side bevore everything gets really fixed and ready for the predeployment.

**Comment by marc-hanheide** [comment]
Let's wait until @cburbridge and @yianni have a first version that's worth looking at.
