### ISSUE TITLE
[infoterminal] feedback & required changes

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#271]
hey there @marc-hanheide @mzillich @TobKoer 
- I took over tobiases infoterminal-observations and found out the following:
  1) the term "Veranstaltungen" needs to be replaced by "Neuigkeiten" in the gereral menu
  2) is there a possibility to create a time out for the submenues - e.g. going automatically back to the main menu after a time of not beeing used.
  people end the interaction in the submenue where the robot remains, not showing its entire offer for others (thats might confusing)

**Comment by marc-hanheide** [comment]
The first one is fixed (when restarted in a few minutes), the second one is a complicated feature request... It will always reset to the start page when it does a new info terminal. Again, if we just go back while people are reading, it will be more irritating than useful. So, I don't think there is an easy answer to that problem.
