### ISSUE TITLE
[walking-group] movebase_state_service died

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#274]
```
[movebase_state_service-10] process has died [pid 24349, exit code -7, cmd /opt/ros/indigo/lib/movebase_state_service/movebase_state_service __name:=movebase_state_service __log:=/home/strands/.ros/log/dac95480-0095-11e5-bb61-00032d225881/movebase_state_service-10.log].
log file: /home/strands/.ros/log/dac95480-0095-11e5-bb61-00032d225881/movebase_state_service-10*.log
```

**Comment by marc-hanheide** [comment]
This was a follow-on from the scitos_node being unresponsive. This got detected by the new [watchdog](https://github.com/strands-project/strands_apps/pull/43), but unfortunately, the `scitos_node` did not come up as inteneded but was stuck at "booting...". Subsequently, it got kill again and then started properly, but then `movebase_state_service` died. A manual restart of the navigation in tmux solved that issue. The robot was massively mis-localised (15 m off), but thought it was very confident about its position. Manual position injection as needed.
@TobKoer was not able to control by joystick, so I did it remotely. Maybe new batteries needed.

**Comment by cdondrup** [comment]
Regarding the joystick, maybe setting up or updating (https://github.com/strands-project/scitos_apps/commit/72e1112c7a0988d5faa2576ce4c5eb735f4e0905#diff-ea96a46c672680c6c7951d698e6b4436) the udev rules would help. I noticed that sometimes it needs a reboot before the joystick is recognised correctly.
