### ISSUE TITLE
[AAF deploy] - errors 

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#275]
Hey there, 

unser Henry steckt mal wieder fest – error response am screen – kann sich da bitte jemand von euch dazuspielen.

Aber mal wieder typisch, wolfgang verlässt die szenerie und henry streitk ^^

Lg Denise

**Comment by mzillich** [comment]
@ToMadoRe can you log in and check? I am stuck in meeting

**Comment by cdondrup** [comment]
We're on it. The chest calibration was lost. Trying to fix it but the internet is too slow over there...
