### ISSUE TITLE
aaf database

### ISSUE THREAD

**Issue by hawesie** [strands-project/aaf_deployment#281]
When you're finished with the deployment, please can you make bits of the database available on ownCloud? I don't need all of it, but the message store collections  nav_stats, task_events, and scheduling_problems would be a great start. (using mongoexport)

**Comment by marc-hanheide** [comment]
I dump the replication database and uploaded it: https://lcas.lincoln.ac.uk/owncloud/index.php/apps/files?dir=%2FSTRANDS%20data%2Fdatasets%2FAAF_y2%2Fmongodumps%2Fmessage_store_aaf_export_control-pc_2015_06_18

Pull all the splits form owncloud and put them back together with `cat message_store.tgz.splitaa message_store.tgz.splitab message_store.tgz.splitac > message_store.tgz`, then untar and import into a mongo db. It misses the last day, as that one had not been replicated yet and I didn't have a look myself, yet. So you might want to wait a bit as well.
