### ISSUE TITLE
aaf timing info

### ISSUE THREAD

**Issue by hawesie** [strands-project/aaf_deployment#282]
For the review analysis, please could someone provide me with:
- [ ]  The start and end datetime of the whole deployment (i.e. when you think I should count stats from and when I should stop)
- [ ] The working hours of the robot, i.e. 9am - 5pm
- [ ] What days the robot took off due to application constraints (e.g. weekends)
- [ ] A list of datetimes when the robot started and ended runs. It looks as if the  code for #143 was not always triggered as the data that mark shared only has 3 complete routines, but lots of partial ones (typically ones that start but don't end)

**Comment by cdondrup** [comment]
- Start date: 18/5/15
- End date: 17/6/15
- Working hours: 8 am - 5 pm local time Vienna
- Days off:
  - 23/5
  - 24/5
  - 25/5
  - 30/5
  - 31/5
  - 4/6
  - 6/6
  - 7/6
  - 13/6
  - 14/6
  
  Robot provided info-terminal at the charging station but wasn't allowed to leave during these days.

About the last point I would need to see a list of the beginning and end dates of the runs, maybe @marc-hanheide knows.

@marc-hanheide, please check if I missed something.

**Comment by marc-hanheide** [comment]
It actually was active 9am-9pm
