### ISSUE TITLE
Wheelchairs/sticks at AAF

### ISSUE THREAD

**Issue by TobKoer** [strands-project/aaf_deployment#285]
@marc-hanheide @mzillich @bleibe @lucasb-eyer @denisehe 

As has been discussed during the review meeting, we can do studies/data colection with wheelchairs (maybe even real patients).
The vienna robot will be with us until Friday morning, so Thursday would be good for any activities in this direction.
However, what exactly is needed from your side? Videos? Videodata captured by the robot itself? 
Might do if we use the wheelchairs ourselves (probably can be organised more easily).

**Comment by lucasb-eyer** [comment]
@Pandoro and me discussed this and would be willing to work on it.

We think that in the end, we'll have to go there ourselves and record some data, because possibly we want to record very specific scenarios difficult to describe. But what would already help us immensely in planning and possibly prototyping are RGB-D video, laser and odom (tf) recordings of moving wheelchairs with someone in them, recorded from the robot itself. I can give you commands on how to start and stop the recording of all necessary topics tomorrow evening.

_But_, due to vacations, summer-schools and nearby deadlines, and also the fact that it's not our actual research topic, there will be some latency (in the order of months) before we start with that. @Pandoro correct me if I'm wrong or missed something.

**Comment by Pandoro** [comment]
@lucasb-eyer  summed up everything perfectly.

What I would like to add, road trips are fun, but if possible it would be nice to use Werner/Henry for this.

**Comment by mzillich** [comment]
Yup, that should not be a problem.

**Comment by TobKoer** [comment]
@lucasb-eyer @Pandoro @mzillich @denisehe 
So, shall we plan for wheelchair recordings via Henry at AAF on Thursday?

Real patients? (cannot promise 100%) or just "anyone" in a wheelchair?
The sooner the details the better ;-)

**Comment by marc-hanheide** [comment]
Hi

I can give you remote access to Werner so you collect the data you need.

Marc

**Comment by marc-hanheide** [comment]
That said, remember to also store laser scans and all of tf.

Marc

**Comment by lucasb-eyer** [comment]
> That said, remember to also store laser scans and all of tf.

Yep, that was already included in my original post :) We actually have much higher hopes in laser than in RGBD for this, but we'll see. Details will follow tomorrow, and remote might be useful -> PM me on gitter.im.

**Comment by TobKoer** [comment]
@lucasb-eyer @Pandoro @mzillich @denisehe @marc-hanheide  

Hi -
apparently TUW will not be involved tomorrow. 
What I can offer now is that at best AAF organises a wheelchair and (if needed) someone from us can move the wheelchair/in the wheelchair and you record the data remotely. Organising real patients and getting their consent is a bit too short notice now, unfortunately, but maybe we can ask patients ad-hoc tomorrow. 
However, there are time constraints on my side, so that it would be best if we plan this for tomorrow before noon. The question is, what you really need now and what has to be done with the robot exactly (it might need to recover from tonight's night run, though ;-) )
Otherwise we should rather plan a systematic capturing of data in autumn (possibly before the GA).
The current status indeed is that an improvement of navigation/reduction of bumping into wheelchairs/feet has been called for by the hospital management. Otherwise next deployments ar at risk of being very limited/called off.

**Comment by TobKoer** [comment]
@lucasb-eyer @Pandoro @denisehe 

hey,
I suggest we start a hangout tomorrow around 9:00 for the data capturing.

Okay for everyone?

**Comment by lucasb-eyer** [comment]
whoa that's heavy, but I'll do my best to make it :)

**Comment by TobKoer** [comment]
@lucasb-eyer 
okay, make that 09:30 ;-)

**Comment by marc-hanheide** [comment]
@lucasb-eyer what is the status of this, we plan a pre-deployment 6-10 Feb 2016 at AAF where this is supposed to work :-) Can you comment please and check if you can be available for that?

**Comment by lucasb-eyer** [comment]
See email.
