### ISSUE TITLE
update the info screen according to feedback

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#287]
https://docs.google.com/document/d/16a7nOE-UchIGuOqc9v7XzLY1ZqCxY6rl4PqxY0NJ6CE/edit?usp=sharing
- [ ] menu for residents (to be discussed by @denisehe and @TobKoer )
- [x] news about internal events (section in wordpress)
- [x] information about activities (section in wordpress)

**Comment by TobKoer** [comment]
@marc-hanheide @gestom 
please also implement the highlighting of icons of the info-screen menu when something has been updated.
Even if there won't be updates every day, this might be a nice visual cue for residents to press the button again and see what's new.

**Comment by marc-hanheide** [comment]
That might actually not be easy to do. What do you define as "new"? And, is it still new when somebody pressed it? We don't know if it's the same person...

**Comment by TobKoer** [comment]
You've got a point there @marc-hanheide 
We might consider a timespan (e.g. one day); but if it's too tricky we can leave it for the time being, maybe we come up with a solution in the Y4 deployment.

**Comment by marc-hanheide** [comment]
Idea: utitlise existing HdB news to populate news section automatically:
- use facebook feed from https://www.facebook.com/hausderbarmherzigkeit/ as news source 
- empower PR people to write to https://henrystrands.wordpress.com/ themselves

Question: Is facebook enough or do we still also need the "old" way of adding further news?

Try to add one photo per post.

**Comment by TobKoer** [comment]
I've talked to PR people recently and there was little enthusiasm about adding NEWS to the robot on their own; yet if we present them with an easy way, it might be worth trying again. 
What I have discovered during that interview was also that a lot of internal events that might be potentially interesting for residents are not always communicated via the PR department! Apparently information policy is pretty decentralised at HdB. Therefore, if we want to really promote internal events BEFORE they have taken place, the PR department/facebook will not be a good solution. 
What it boils down to is that most likely AAF will have to add internal news; but then again we would be the users of the robot (news, menu update, bellbot controlling etc.) more than anybody else. So I'm not sure that is a good way either.

**Comment by marc-hanheide** [comment]
- Have both menus, "SANA" and "Bewohner". 
- @gestom had plans to write a script that extracts this from the PDF...
- let's try to harvest the facebook for news https://www.facebook.com/hausderbarmherzigkeit/
- info terminal contains the video

**Comment by marc-hanheide** [comment]
see #301 for an update on the news section which is now fully automatically populated from [facebook](https://www.facebook.com/hausderbarmherzigkeit/) and ORF Vienna news
