### ISSUE TITLE
video preparation

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#290]
concept: https://docs.google.com/document/d/1Gz5AAUm-BYgTmrcb8zsp6Nst7LeIYQRZAAC3bAj4OtQ/edit?usp=sharing
- we have a screen in the lobby
- we have permission to record
- the recording people should probably arrive on Monday/Tuesday

**Comment by marc-hanheide** [comment]
OK, so Dan won an award... and the video is late. I gave him to Tuesday to deliver. Then I'll add the subtitles.

**Comment by marc-hanheide** [comment]
@TobKoer so you know

**Comment by TobKoer** [comment]
@marc-hanheide 
OK, congrats to Dan. 
We are not in a total hurry, because we won’t have the screen in the lobby before March 21st. Also the embedding a video in the screen presentations in the cafeteria causes more technical problems than suspected – our ICT department is figuring out why it’s not working…

Let us know if you need input for the subtitles.

Cheers,
Tobias.

**Comment by marc-hanheide** [comment]
Finally... here's a first draft (with long breaks so still needs final edit), but with subtitles I crafted in German. I seek feedback on this one from @TobKoer and @denisehe, please.

The video is _not_ in the final resolution or quality. I rendered it small, so don't worry about the quality. Look at the content and text please.

Download from https://lcas.lincoln.ac.uk/owncloud/index.php/s/wpGZ3zaJdGxCr4c (you could also try if this works on the screen, please)

**Comment by marc-hanheide** [comment]
Oh, @hawesie you may want to take a glimpse as well...

**Comment by denisehe** [comment]
Good Morning @marc-hanheide , i saw the video my comments below:
1. in the bellbot section the old screen is shown, this should be updated to the new one. 
2. the written info, that the bellbot can be ordered via the reception is not correct any more, as far as I am informed this was cancelled and the bellbot is just scheduled for the bigger events. 
3. When informing viewers that henry perceives his surroundings via camera and sensores there is a closeup of his eyes in the video - in this case i think it would be nicer to have pictures of the cam and the sensor, if there is any footage...otherwhise its a bit leading towards anthropomorphization

AAAND:
1. I reallly love the video! :-) really nice footage!
2. the idea to blend in screenshots of the interface explaingn what to do, really very good!
3. really cool is also the section where we all move towards the robot and where you inserted the virtual map with the surrogates - cause that really showes that the roboter does not see individuals but merely figures! :-)

:+1:

**Comment by TobKoer** [comment]
@marc-hanheide 
Hey, the good news is, the format is played by that odd screen, the bad news is, most is dstrubed by awful colourful dots and squares.
![imag0057 1](https://cloud.githubusercontent.com/assets/4354921/13982107/624232b8-f0e8-11e5-8a03-ae44fcf72914.jpg)

![imag0059 1](https://cloud.githubusercontent.com/assets/4354921/13982119/77e43fa8-f0e8-11e5-914a-7a4c758366ae.jpg)

**Comment by marc-hanheide** [comment]
Oh, man... Well, I have a few more option to try... Will update you with the latest once I have the video from Dan.

**Comment by TobKoer** [comment]
General feedback: this looks really good and well-made!!! Congrats to everyone involved.

@denisehe has already mentioned the main points.
@marc-hanheide 
Two further issues I noticed are:
- sometimes the longer subtitles should be shown a bit longer (for older readers who might need some more time), so pace of the video can be relaxed.
- One information I think was missing: Henry is not able to talk or understand speech (I have recently been asked again if at one point during the deployments people will be able to speak to Henry and why that isn't so....)

**Comment by marc-hanheide** [comment]
@TobKoer I timed the subtitles very much according to typical guidelines, aiming at 8 characters per second maximum, which is deemed very long. So, if we want to display longer and having the same content, then we need more video material, and we need more overall time, obviously. 

The issue about speech is true... Just didn't find a good way to include it yet, maybe Dan has an idea?

**Comment by marc-hanheide** [comment]
So @DanDavisonCam is now in here as well, so we can all communicate more effectively.

**Comment by DanDavisonCam** [comment]
Hi guys, I'm making the adjustments that have been outlined, however I'm not sure of a way of answering the speech issue. I know we didn't get any footage of somebody speaking to the robot...

**Comment by marc-hanheide** [comment]
Maybe, can we change the bit where the robot's head is shown (at the charging station) to talk about it, and reduce the talk about the sensors in that shot. That's a bit repetitive anyway, as it comes later again

**Comment by DanDavisonCam** [comment]
In terms of showing the sensor, I have a small clip of it, but in a separate location, I can add that in wherever you guys would want it, outside of that, I've made the adjustments, apart from showing the eyes, which again, there's no clip of the sensors apart from early on, just outside where the work was being done.

**Comment by marc-hanheide** [comment]
I think, before we show the internal processing (the PiP map of the robot) it would be best to talk about the sensors. So, just add a few seconds of close ups of whatever you have that could relate to sensors there. Then we talk about the inability to recognise speech on the head close-up. Makes sense?

**Comment by DanDavisonCam** [comment]
I'm adding in a few shots of the camera and sensor after the map

**Comment by DanDavisonCam** [comment]
Before, sorry
I'll upload it within the next hour

**Comment by DanDavisonCam** [comment]
uploaded

**Comment by TobKoer** [comment]
Okay, sounds good.

**Comment by marc-hanheide** [comment]
OK, I again prepared a [draft version](https://lcas.lincoln.ac.uk/owncloud/index.php/s/XxvBrY5wxAQ4G6u) with subtitles for you to download.

The subtitles are in [`aaf-DE.srt.zip`](https://github.com/strands-project/aaf_deployment/files/188683/aaf-DE.srt.zip) for @DanDavisonCam to work with. I have not created an English version yet, as I will only do this once we have a final edit.

I marked some part as `[-- to be removed --]` as I thought they can't be used very well and are not needed.

Then it also needs to following:
- [ ] Logos of [STRANDS](https://lcas.lincoln.ac.uk/owncloud/index.php/s/oGy7ezBSJ3VfKtq), and all the [partners](https://lcas.lincoln.ac.uk/owncloud/index.php/s/3vnWcN6O8hQFisj)
- [ ] Hi-res export
- [ ] A version without the scene where the robot drives past the resident sat in front of the cafeteria (privacy issues) for public display
- [ ] A version with English subtitles

**Comment by marc-hanheide** [comment]
again for @denisehe and @TobKoer to look at and for @DanDavisonCam to take the next step.

**Comment by denisehe** [comment]
ja stimmt - gehört hierher!

Hi @marc-hanheide,
my feedback:

```
the information that the bellbot can be called from the reception is still in but as far as i know not available in this form

I would replace the phrase "effektiv einsetzten im HB" - rather I would say "soll herausgefunden werden, in welchen Bereichen der Roboter eine Unterstützung sein könnte"

In the end a short final sequence would be nice, eighter the robot driving off and seen from behind or a close up from its eyes that open and look away ...(but such a scene is already in)

the sequence that is marked as "to be eliminated" wasn't that the scene with the bumper?
I think it would be well worth it to have that sequence but maybe after the sequence where we explain that the robot tries at its best to avoid obstcles - and then insert this scene - in case it does not work there is this bumper as a last savety - that it does not hurt and will stop immideately.
```

:-)

**Comment by marc-hanheide** [comment]
OK, 

so here is an updated subtitles file: 
[aaf-DE.srt 2.zip](https://github.com/strands-project/aaf_deployment/files/189313/aaf-DE.srt.2.zip)

Below the actual content of the file, for last corrections. Also, I made some edit suggestions for @DanDavisonCam in there. If they are unclear, please ask for clarifications here.

```
1
00:00:00,000 --> 00:00:08,340
Henry ist ein Service-Roboter, der im Rahmen des STRANDS Projektes im Haus der Barmherzigkeit auf seine Alltagstauglichkeit getestet wird.

2
00:00:08,700 --> 00:00:12,860
Er soll Ihren Alltag bereichern und aktuelle Informationen anbieten.

3
00:00:12,860 --> 00:00:17,100
Henry wird im Haus der Barmherzigkeit herumfahren und seine Dienste anbieten.

4
00:00:17,100 --> 00:00:20,900
Drücken Sie einfach auf die Knöpfe auf dem Bildschirm, ...

5
00:00:20,900 --> 00:00:26,460
... um sich Informationen anzeigen zu lassen.

6
00:00:26,460 --> 00:00:29,180
Zum Beispiel zum aktuellen Wetter in Wien,

7
00:00:29,500 --> 00:00:32,300
oder die neusten Nachrichten,

8
00:00:32,300 --> 00:00:35,460
oder das aktuelle Mittagsmenü.

9
00:00:35,460 --> 00:00:43,540
Wenn Sie genug von Henry haben, lassen Sie ihn einfach stehen, er wird sich dann wieder auf den Weg machen.

10
00:00:45,740 --> 00:00:51,340
Henry kann auch Besuchern und Gästen den Weg im HdB weisen.

11
00:00:51,340 --> 00:00:58,940
Geben Sie dazu einfach das Ziel, zum Beispiel das Büro einer Person oder eine Raumnummer, ein...

12
00:00:58,940 --> 00:01:04,820
... und lassen Sie sich vom Roboter führen.

13
00:01:04,820 --> 00:01:12,420
Diese Funktion wird durch die Forscher aktiviert, wenn Besucher Begleitung durch den Roboter wünschen.

14
00:01:12,420 --> 00:01:19,900
Am Ziel angekommen, verabschiedet sich Henry von Ihnen und geht wieder seinen anderen Aufgaben nach.

15
00:01:20,020 --> 00:01:24,340
Henry ist nicht ferngesteuert, sondern fährt und entscheidet selbstständig,

16
00:01:24,340 --> 00:01:27,740
auch, wann es es Zeit ist, seine Batterien wieder aufzuladen.

17
00:01:27,740 --> 00:01:32,340
Henry kann zu Ihnen sprechen, aber leider kann er Sie nicht verstehen.

18
00:01:32,340 --> 00:01:37,780
Interagieren Sie mit ihm einfach mit Hilfe des Bildschirms.

19
00:01:38,020 --> 00:01:42,820
[-- to be extended and moved towards the end (marked as A)--]
Sollte Henry Ihnen zu Nahe kommen und Sie berühren,

20
00:01:42,820 --> 00:01:54,340
[-- this is a blank which should show the actual bumper event, ideally with a close up of the rubber rim at the bottom --]
so wird er durch einen Sicherheitsschalter am Weiterfahren gehindert.

21
00:01:54,340 --> 00:01:59,580
Henry fährt selbstständig im Haus umher,

22
00:01:59,580 --> 00:02:05,940
und versucht dabei stets, Sie nicht zu behindern, und Hindernisse zu umfahren.

23
00:02:05,940 --> 00:02:09,660
Henry ist ein Roboter, durch den Forscher herausfinden wollen,

24
00:02:09,660 --> 00:02:14,700
in welchen Bereichen Roboter eine Unterstützung sein könnten.

25
00:02:14,700 --> 00:02:20,380
Henry hat mehrere Kameras und andere Sensoren,

26
00:02:20,380 --> 00:02:27,340
mit denen er seine Umgebung und Menschen wahr nimmt.

27
00:02:27,540 --> 00:02:33,540
So kann Henry Sie "sehen", und er weiß auch jederzeit wo er ist,...

28
00:02:33,540 --> 00:02:37,020
da er eine Karte des Hauses erstellt hat.

29
00:02:37,020 --> 00:02:40,740
So kann er sich frei bewegen, und Ihnen zu Diensten sein.

30
00:02:40,740 --> 00:02:42,420
[-- insert A here --] 
So kann er sich frei bewegen, und Ihnen zu Diensten sein.

31
00:02:42,420 --> 00:02:50,380
[-- insert A here --] 

32
00:02:50,400 --> 00:03:00,000
Sollten Sie Bedenken bezüglich des Roboters haben, wenden Sie sich bitte an das STRANDS Team oder die Rezeption.
 [-- Extend this with an additional scene of the robot driving off and leave subtitles on for this --]

```

**Comment by denisehe** [comment]
thanks to our amazing internet security I cannot open the file :-/

**Comment by denisehe** [comment]
And in terms of bellbot, was it not agreed on that in case of external events the robot will be sheduled and therefore waiting in the lobby infront of the reception?

**Comment by denisehe** [comment]
I would insert phraseas about the bumper after the scenes where it is explained that he tries to avoid obstacles, cause it would fit more to the scenario that he tries to awoid but just in case it happenes there is the bumper

**Comment by denisehe** [comment]
Ah and the last phrase: "Bedenken wegen des Roboters"

I would say : "Fragen oder Anmerkungen zum Roboter haben dann...." 

sounds more positive

**Comment by marc-hanheide** [comment]
regarding bellbot: yes, but that's too technical for this video.

**Comment by denisehe** [comment]
Or we write: "Bei großen Veranstaltungen erwartet Henry Besucher an der Rezeption um ihnen den Weg zu den Räumlichkeiten zu zeigen. Man muss nur den Raum oder die gewünschte Person am Bildschirm eintippen, dann bringt Henry Sie zum Ziel. 

or something like that...

**Comment by marc-hanheide** [comment]
@DanDavisonCam when do you think you can get those edits to me?

**Comment by TobKoer** [comment]
@marc-hanheide, @DanDavisonCam  
BTW file not supported by the screen. :-/
FYI it's a videoscreen by showroom.at, but I couldn't find any more helpful data regarding the video format needed.

**Comment by TobKoer** [comment]
@march-hanheide
Hi, i the subtitles above also a few typos
at 7 it should be "neueste" not neuste
at 19 it's "zu nahe" not zu Nahe.

**Comment by cdondrup** [comment]
"nahe"? Shouldn't it be "nah"?
http://www.duden.de/rechtschreibung/nahe_naechst_zukuenftig

**Comment by marc-hanheide** [comment]
Right, typos... @DanDavisonCam rather than me adding another subtitles file, I think it's best if you correct those in the "beta" version. So, what's your status?

**Comment by DanDavisonCam** [comment]
Apologies for the late reply, I've had my laptop being repaired, the files are uploaded, "Strands video +++++" and "strands video alternative" that has the clip removed that was mentioned.

Let me know if this is the final version, and whatever you may need doing with the subtitles

**Comment by marc-hanheide** [comment]
I can't find "Strands video +++++" or the alternative...

**Comment by DanDavisonCam** [comment]
reuploaded

**Comment by TobKoer** [comment]
@DanDavisonCam  
Hi, can you provide me with the link?

**Comment by DanDavisonCam** [comment]
https://lcas.lincoln.ac.uk/owncloud/index.php/s/52j1EI3YXm11fPi

**Comment by TobKoer** [comment]
@DanDavisonCam 
Okay the latest version (uploaded two days ago) looks fine for me, but that's without subtitles at the moment, right?

**Comment by marc-hanheide** [comment]
@DanDavisonCam, first apologies I didn't come to look at this. However, I found your latest version does not address all the issues raised, does it. There were a few more edits requested as indicated in the subtitles file. Maybe this wasn't the latest version??? 
Here's an updated version for the current movie with suffix `+++++`: 
[aaf-DE+++++.srt.zip](https://github.com/strands-project/aaf_deployment/files/216776/aaf-DE.srt.zip)

The part in the middle where the robot is about to make physical contact needs to be extended. There is a long black period ("blank"): `00:01:48,920 --> 00:02:00,440` , which needs to be changed as indicated below. In particular, I highlighted the following requested edits (with times indicated), which were already requested in the previous iteration:

```
19
00:01:44,120 --> 00:01:48,920
[-- to be extended and moved towards the end (marked as A)--]
Sollte Henry Ihnen zu Nahe kommen und Sie berühren,

20
00:01:48,920 --> 00:02:00,440
[-- this is a blank which should show the actual bumper event, ideally with a close up of the rubber rim at the bottom --]
so wird er durch einen Sicherheitsschalter am Weiterfahren gehindert.
```

Then, towards the end, I asked to have the scene 19 and 20 moved, and the video slightly extended with a "drive-off" scene:

```
31
00:02:48,520 --> 00:02:56,480
[-- insert A here --]

32
00:02:56,500 --> 00:03:06,100
Sollten Sie Fragen oder Anmerkungen zum Roboters haben, wenden Sie sich bitte an das STRANDS Team oder die Rezeption.
 [-- Extend this with an additional scene of the robot driving off and leave subtitles on for this --]
```

If this is unclear, @DanDavisonCam please get in touch, we can talk about this to clarify it.

**Comment by DanDavisonCam** [comment]
Sorry about that Marc, I'll push to try and sort this today!

**Comment by marc-hanheide** [comment]
OK, much appreciated, as I said, if you want to talk about it to clarify, I'm available.

**Comment by TobKoer** [comment]
@marc-hanheide 
Hi please take care of typos:
It should read

19
00:01:44,120 --> 00:01:48,920
[-- to be extended and moved towards the end (marked as A)--]
Sollte Henry Ihnen zu nahe kommen und Sie berühren,

32
00:02:56,500 --> 00:03:06,100
Sollten Sie Fragen oder Anmerkungen zum Roboter haben, wenden Sie sich bitte an das STRANDS Team oder

**Comment by marc-hanheide** [comment]
@DanDavisonCam ??

**Comment by DanDavisonCam** [comment]
Sorry about that, rendered it overnight and forgot to upload, filename is Strands Video Final (fingers crossed!) Let me know if any more changes are necessary!

**Comment by marc-hanheide** [comment]
[all subtitles files](https://github.com/strands-project/aaf_deployment/files/219821/aaf-subtitles-final-DE-EN.zip) aligned with [`Strands video Final.mp4`](https://lcas.lincoln.ac.uk/owncloud/index.php/apps/files/ajax/download.php?dir=%2FSTRANDS%20data%2Faaf_video&files=Strands%20video%20Final.mp4) (only accessible with owncloud login)

**Comment by marc-hanheide** [comment]
looks good so far, just re-coding a version with subtitles and then this is good to be tested

**Comment by marc-hanheide** [comment]
OK, I finished the recoding and uploaded this now. So, first, @TobKoer can you test it, please? There are two versions, one has the German subtitles burned in (means they are part of the rendering), and the second has both English and German subtitles, but not rendered, so they can be chosen by the player.
- [full version with "burned-in" German subtitles](https://lcas.lincoln.ac.uk/owncloud/index.php/s/jWzna8B7vaiIbvz)
- [full version with selectable German and English subtitles](https://lcas.lincoln.ac.uk/owncloud/index.php/s/qutC53N8XbMkqx6)

Also pinging @hawesie who wanted to have a look at the videos.

**Comment by marc-hanheide** [comment]
and here: https://www.youtube.com/watch?v=1t3CQuo63k8 (not publicly searchable on youtube)

**Comment by TobKoer** [comment]
@marc-hanheide,
the video and subtitles look really good to me now. 
Unfortunately, however, both versions are not running on the screen (only on laptop) :-/
Also, we will not have the screen from end of next week, because it is needed by the PR department again.

**Comment by marc-hanheide** [comment]
What??? We won't have the screen now we finally have the video? Or just not for one day?
 Can you let me know again what system it is running?

**Comment by TobKoer** [comment]
@ marc-hanheide
Yes, I'm sorry, I can't help that, since the screen belongs to the PR department and they already stated beforehand they might need it at some points. After all, we are already a good month into the deployment now without a video. The screen will definitely be gone for at least one week starting this Friday and then probably once ore some time in May.

As mentioned, the system is not explained anywhere. The screen is provided by http://www.showroom.at
it also came with a small manual, but there it only says "supports MP4 files"...well not really apparently :-/
I also asked the guys from the PR department - they never used it for videos but only for photo slideshows.

**Comment by marc-hanheide** [comment]
OK... slightly frustrating, but let's just try to make it work anyway. @cdondrup is it worthwhile putting it onto the robot to be used in the walking group? I could also put it in info-terminal, but that would require an additional button and page... Opinions?

**Comment by cdondrup** [comment]
I'm sure the screen supports any kind of file format it's just PowerPoint that doesn't. I don't think it makes much sense to put the video in the walking group because that means that the participants would see it but for them it wouldn't be helpful I guess.

I think it makes most sense to have it in the info terminal like a "Wer bin ich?" button.

**Comment by TobKoer** [comment]
@marc-hanheide 
in any case, I don't think it is "lost labour", because we still have the final deployment where we can 
a) have the video on the robot anway
b) try to revive the screen idea again (right from the start).

**Comment by marc-hanheide** [comment]
No, I didn't think it would be lost. But we should try to put it on the screen.

**Comment by marc-hanheide** [comment]
I have created another video, this time encoded "windows-friendly" as a WMV. Could you give it a try, @TobKoer, please?

https://lcas.lincoln.ac.uk/owncloud/index.php/s/ou8xDvGh8qL8bII

**Comment by TobKoer** [comment]
@marc-hanheide,
thanks for all the effort. WMV unfortunately is not recognised/supported.
![imag0065](https://cloud.githubusercontent.com/assets/4354921/14715260/79290544-07e8-11e6-9944-2e92b78682f1.jpg)

The manual is not very informative either. As we both know, we have already tried various MP4 versions of the video.
Before we break our heads further over that crappy screen, I suggest we leave the video as part of the info-terminal for the deployment (apparently quite popular new feature).

What we could offer is to install an ordinary laptop screen in the library section from the start of the final deployment, which, however, is not a very elegant solution, but apparently nobody knows how to make videos work on the other screen from the PR department. It looks good but it just does not work.

**Comment by marc-hanheide** [comment]
OK, another format to try, please: https://lcas.lincoln.ac.uk/owncloud/index.php/s/bMzhO99CZCMz9QX @TobKoer @denisehe
