### ISSUE TITLE
Rosbags for mapping dataset

### ISSUE THREAD

**Issue by Jailander** [strands-project/aaf_deployment#291]
@gestom and @jailander want to create bags of the robot's odometry and laser reading to be able to create slam maps of AAF at different times of the day for this purpose we would like to create rosbags with different topics recorded that could be used later to rebuild the maps afterwards. These topics are:
- `/tf`
- `/scan`
- `/odom`
- `/amcl_pose`
- `/robot_pose`
- `/current_node`
- `/current_edge`
- `/map`
- `/topological_map`

**Comment by marc-hanheide** [comment]
rosbags or mongo_log? And... did you go to buy a suitable hard drive?

**Comment by marc-hanheide** [comment]
This is fixed?
