### ISSUE TITLE
bellbot improvements

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#293]
- add more information on how to use
- use better names for waypoints

**Comment by TobKoer** [comment]
- change waypoint in front of reception (bellbot starting position) and move more to the right?!

**Comment by lobinho** [comment]
- Add a button to change selected destination:
  After choosing a destination there is no proper way to change this selection. If you accidentally select a wrong destination you would probably press delete or anything else which does not work in that case. Nothing happens until you press the button to start the navigation ("Bring mich zum Ziel"). In that case the input is refused and the scenario starts again from the start without navigating. This could be confusing and might seem as it wouldn't work. While pressing "Bring mich zum Ziel" after choosing a destination without reusing the keyboard actually starts the navigation of course.

**Comment by marc-hanheide** [comment]
@lobinho I just tried, and the delete button worked perfectly for me. I cannot reproduce the problem...

**Comment by marc-hanheide** [comment]
But I added a proper "Löschen" button anyway and removed the confusing keys on that keyboard. It looks like this now:

![image](https://cloud.githubusercontent.com/assets/1153084/13901465/d8b86b68-ee24-11e5-91fe-633b84567194.png)

Better? @TobKoer @lobinho ?

**Comment by marc-hanheide** [comment]
Just decided that a cancel button "abbrechen" is actually not useful... So, I'll take that out again.

**Comment by marc-hanheide** [comment]
new version:
![image](https://cloud.githubusercontent.com/assets/1153084/13901512/bfb708d4-ee26-11e5-9fd7-e0d1207e3c26.png)

**Comment by marc-hanheide** [comment]
https://github.com/strands-project/strands_hri/pull/139 implements this.

**Comment by denisehe** [comment]
The interface looks really more easy going now!

Just one wish: could you please enlarge the letters of the explanatory text? Think that would be nicer to read.

Cheers Denise

**Comment by lobinho** [comment]
Looks very good. Since the buttons that caused problems were removed it should be fine now. I will give it another try next time bellbot is running.

**Comment by TobKoer** [comment]
Yes, that could do. Maybe change the order first "zeil loeschen" and then "Losgehen"?
Also agree with bigger letters for explanatory text. We have to keep in mind that some visitors are also older persons/relatives of residents.

**Comment by lobinho** [comment]
We did some more testing and have some suggestions for improvement:
- Add a symbol to the backspace and space button. They do work but symbols would be more intuitive.
- Move the destination input field below buttons Los gehen and Ziel loeschen. Otherwise the autosuggestions would cover the buttons.

**Comment by marc-hanheide** [comment]
My bad... I tested with the wrong resolution, I notice now... 
I'll check for the other minor issues right now

**Comment by marc-hanheide** [comment]
fixed in https://github.com/strands-project/strands_hri/pull/141
