### ISSUE TITLE
Bellbot speech output has wrong timing

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#296]
The speech output is given at the wrong times, e.g. the greeting asking people to type a destination is only given after the destination has been typed and the Go button is pressed. Same for the finishing speech.

**Comment by marc-hanheide** [comment]
Who is in charge of this? @yianni ?

**Comment by gatsoulis** [comment]
Not me on this and not sure. Blame maybe can find out?

**Comment by cdondrup** [comment]
The [voice output](https://github.com/strands-project/strands_hri/blob/hydro-devel/bellbot_action_server/scripts/voice_output.py) is mine but that just listens to `bellbot_state` and says a predefined sentenced according to that base on a [config file](https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_bellbot/conf/bellbot_voice.yaml) which means that either the states are published at the wrong time or my script is wrong.

**Comment by marc-hanheide** [comment]
can you investigate, @cdondrup ?

**Comment by cdondrup** [comment]
I'll try.
