### ISSUE TITLE
Bellbot does not like utf8

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#297]
When selecting "Tobias'" office via his name, the bellbot complains that:

```
[ERROR] [WallTime: 1455110920.835345] error when calling bellbot service. 'ascii' codec can't encode character u'\xf6' in position 64: ordinal not in range(128)
```

When pressing the Go button nothing happens.

**Comment by marc-hanheide** [comment]
Uh, I hate unicode... Can we work around this with "Koertner" for now, please?

**Comment by cdondrup** [comment]
That means @Jailander has to change all the meta information of the map.

**Comment by Jailander** [comment]
:( I just opened my mail to find this,  ok first thing Monday

**Comment by Jailander** [comment]
Ooops completely forgot about this, @marc-hanheide how can i get access to werners map?? can you remind me?

**Comment by marc-hanheide** [comment]
[maps.zip](https://github.com/strands-project/aaf_deployment/files/156560/maps.zip)

**Comment by Jailander** [comment]
@marc-hanheide fixed map is here, 
[aaf_deployment16.zip](https://github.com/strands-project/aaf_deployment/files/156811/aaf_deployment16.zip) to insert use `rosrun topological_utils load_yaml_map.py -f /path_to_file/aaf_deployment16.yaml`

**Comment by marc-hanheide** [comment]
@Jailander I send this email with the instruction how to share files with henry so you can do it yourself ;-)

**Comment by Jailander** [comment]
Ok :)

**Comment by marc-hanheide** [comment]
fixed? please close if so.

**Comment by Jailander** [comment]
it should, but haven't tested it, there are no more weird German characters in the topological map though
