### ISSUE TITLE
logging

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#300]
- how much are we logging per day?

**Comment by marc-hanheide** [comment]
@nilsbore

**Comment by nilsbore** [comment]
I'll look into this! Can I get into Werner? I'll text you on gitter.

**Comment by nilsbore** [comment]
We are logging about 500 MB/h => 12 GB/day. It seems most of this consists of the scan topic logging.

**Comment by marc-hanheide** [comment]
Great, thanks. That seems reasonable with the 8Tb storage we have for 60 days. I assume this is uncompressed so for later storage it should also be fine. @jailander and @gestom how much you guess you will add in rosbags and scans?

**Comment by gestom** [comment]
In terms of rosbags, we are logging approx/ the same amount per day as @nilsbore - it was 0.5 TB/month.

**Comment by marc-hanheide** [comment]
:+1: all good then. We should monitor this, though. I already have a cron job that emails when space gets below 80%.

**Comment by marc-hanheide** [comment]
Though it needs to be modified to also check /storage

**Comment by TobKoer** [comment]
@marc-hanheide, @nilsbore, @hawesie 
HI, just to bring this up once more, this is what AAF is interested in/would need for evaluation purposes (in both care and security scenarios!):
- •   Frequency of use (which task/service is used how often?)
- Error frequency/problems ocurring during task
- which service is used most often?
- changes of use/frequencies over time

**Comment by marc-hanheide** [comment]
appears to be working now, right?

**Comment by nilsbore** [comment]
Yeah, most importantly, it can easily by checked by looking at the topic `/monitored_logs`. It publishes the number of entries logged for each topic in the last 30s together with the total number of topics. Note that it does not do this for `/tf` and `/odom` since they have too many entries to be effectively queried. But tf logging was tested extensively last year.

**Comment by denisehe** [comment]
Hello @marc-hanheide @nilsbore 
i heard you enhanced logging for this year :-)

is it possible to get a overview of how logging happenes this year?

**Comment by marc-hanheide** [comment]
Well... the improvement is that it works this year! I'll include the list of topics that are being logged below. If you want to know more specific what all this is then you need to ask specifically ;-)

```
"/amcl_pose": [0, 3668]
"/chargingServer/result": [0, 5]
"/docking/goal": [0, 9]
"/current_edge": [0, 128]
"/walking_group_fast/result": [0, 0]
"/strands_webserver/display_4/page": [0, 58]
"/undocking/goal": [0, 14]
"/move_base/current_goal": [0, 380]
"/strands_webserver/display_9/page": [0, 0]
"/info_task_server/goal": [0, 54]
"/strands_webserver/display_3/page": [0, 2]
"/current_node": [0, 736]
"/maintenance_task/goal": [0, 0]
"/store_logs/goal": [0, 0]
"/undocking/result": [0, 14]
"/bellbot/cancel": [0, 0]
"/topological_navigation/Route": [0, 43]
"/strands_emails/goal": [0, 0]
"/docking/result": [0, 9]
"/map_updates": [0, 0]
"/walking_group_slow/goal": [0, 0]
"/map": [0, 0]
"/topological_map": [0, 21]
"/speak/goal": [0, 27]
"/strands_webserver/display_8/page": [0, 0]
"/closest_node": [0, 472]
"/topological_navigation/Statistics": [0, 63]
"/bellbot/goal": [0, 0]
"/maintenance_task/result": [0, 0]
"/walking_group_slow/result": [0, 0]
"/strands_webserver/display_6/page": [0, 0]
"/walking_group_fast/goal": [0, 0]
"/chargingServer/goal": [0, 3]
"/walking_group_slow/cancel": [0, 0]
"/store_logs/cancel": [0, 0]
"/charging_task/goal": [0, 0]
"/strands_webserver/display_5/page": [0, 0]
"/strands_webserver/display_7/page": [0, 0]
"/rosout_filtered": [0, 15004]
"/emergency_stop_status": [0, 5]
"/bellbot/result": [0, 0]
"/wifiscanner": [56, 1823549]
"/undocking/cancel": [0, 0]
"/strands_webserver/display_1/page": [0, 1]
"/info_task_server/cancel": [0, 51]
"/docking/cancel": [0, 0]
"/do_backtrack/goal": [0, 3]
"/charging_task/cancel": [0, 0]
"/info_task_server/result": [0, 53]
"/chargingServer/cancel": [0, 0]
"/store_logs/result": [0, 0]
"/strands_webserver/display_2/page": [0, 1]
"/walking_group_fast/cancel": [0, 0]
"/task_executor/events": [0, 2093]
"/charging_task/result": [0, 0]
"/maintenance_task/cancel": [0, 0]
"/info_terminal/active_screen": [0, 232]
"/diagnostics_agg": [30, 534780]
"/info_terminal/task_outcome": [0, 53]
"/strands_image_tweets/goal": [0, 0]
```

**Comment by denisehe** [comment]
ok cool! no that gives a good impression and overlook, for now no more details are required

**Comment by denisehe** [comment]
@marc-hanheide @TobKoer 

okay I have some questions about the detailed logging during the walking groups:

what exactly do you log as 
walking group goal
walking group cancel 

how is this logged, what does it say
with cancel do you mean cancelled by the therapistst?

does task executor/events mean that the system logs failures during execution of a tasks eg. the walking group?

cheers, denise

**Comment by marc-hanheide** [comment]
This just looks when a walking group was started and when it was cancelled in terms of triggered by the scheduler. 
There are many different failures, `task_executor/events` logs event from the scheduler. Then we have `monitored_nav` events (actually logged seperately, so not shown about, as they contain a lot information about failed navigation). We can see from the `task_executor/events` should the therapists click to end the session (however, that is not considered a failure, but indeed a success, form a system's perspective), it's your interpretation that it might be a failure.

**Comment by nilsbore** [comment]
Hey, Denise. Basically those messages are what we use to start and stop the walking group. It is defined in https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_walking_group/action/WalkingGroup.action . I think it's basically parameters (@cdondrop ?) for slow/fast walking group etc. The cancel thing should be when it's cancelled by therapists, yes, but the meaning of this "cancel" is generic for different kinds of robot services. And yes, we are monitoring when the system fails through various messages, some of them are not included in this list.

**Comment by cdondrup** [comment]
What @marc-hanheide and @nilsbore said ;)

**Comment by denisehe** [comment]
Well acutally i do not really understand all these technical backgrounds - easily put:

do we get data from this log in terms of

a) how often did the system crush during the group
b) maybe in percent how long the system is running per session and how long it was non functional/having errors
c) can wee see what the therapists did use the robot for (how many percent of the time did they play music or natural sounds...what they did during breaks (pictures vs. music)?

**Comment by cdondrup** [comment]
Ok, I'm not sure about the error logging but we should get that, right @marc-hanheide ?

Regarding what the therapists did, there are a lot of services, one per button on the interface, so we could log those to get a feeling for what they did.

**Comment by denisehe** [comment]
yes because from a user point of few it doese not matter what failure it was that distrubed the walking group we just need to know if there were failures etc or not.

and of course what the therapists use the robot for....

all the technical details are of no social scientific relevance to us and adresses rather technical quesitons of research.

so anything that could help to retrieves these superficial data for us is enough

a) how often did the system crush during the group
b) maybe in percent how long the system is running per session and how long it was non functional/having errors
c) can wee see what the therapists did use the robot for (how many percent of the time did they play music or natural sounds...what they did during breaks (pictures vs. music)

**Comment by denisehe** [comment]
And how much percent of the time/session the robot was performing and how much percent it was in error mode

that would also be good to know :-)

**Comment by marc-hanheide** [comment]
errors are pretty much events, not durations... not sure what you mean.

**Comment by denisehe** [comment]
I am aware of that - but is it logged how long the robot needed to continue with the task again

eg. one quick error in navigation, calc for some seconds and continue vs. major error system down for 10 min

is that logged?

**Comment by marc-hanheide** [comment]
yes... we can somewhat identify that... e.g. we cn find out for how long it didn't move...

**Comment by denisehe** [comment]
ja - es geht halt prinzipiell darum dass wir veränderungen im rating der therapeuten quantifizierte rückschlüsse auf seine performance in den einzelnen sessions machen können (wie viele errors, weclhe, wie lange etc.) nur so gewinnen die ergebnisse an wert.

**Comment by marc-hanheide** [comment]
that'll be possible. It would have been last year, but unfortunately the logs didn't work. They do know as we are testing and monitoring.

**Comment by denisehe** [comment]
perfect :-)

ups i wrote in german before ^^
