### ISSUE TITLE
Video recording

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#302]
Like last year, we use a white list of nodes to allow video recording only in the administration wing and the lobby. This white list can be generated from the topological map given that the nodes have a certain tag. This tag is still present for all the nodes we used last year but since we added, removed, or moved a few, this needs testing and retagging again. 

To be tested during test run on Tuesday 8/2/16

**Comment by marc-hanheide** [comment]
This still needs testing right?

**Comment by cdondrup** [comment]
Yes
