### ISSUE TITLE
[all Szenarios] Cliff detection

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#31]
Fall prevetions is still an issue to work on - thus I open this issue: 

as we discussed yesterday: @mzillich - when can you come over with a magnetic strip so that we can decide if this is doable at AAF?

@marc-hanheide, @cdondrup @Jailander @cburbridge @hawesie @ToMadoRe @yianni

**Comment by marc-hanheide** [comment]
Please join discussion in https://github.com/strands-project/scitos_drivers/issues/98 I'll close this one as duplicate as we have a discussion on this running over there.
