### ISSUE TITLE
New additional video camera on Henry

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#310]
Dear @marc-hanheide @mzillich @ToMadoRe @cdondrup @TobKoer 

i am back from the other side of the globe and thus fully involved in the preparations for our trial :-)

I have a question: is it possible to change the additional camera that was put on Henry last year 

it would be better to have a camera that
1) also records sound
2) records the movements in a flow not in single frames

this would be especially used to enhance the walking group evaluation!

@mzillich @ToMadoRe do you have such a cam? is it easily possible to get such a thing?
@marc-hanheide is it possible to change the cam in terms of general data saving and systgem set up?

Cheers Denise

**Comment by marc-hanheide** [comment]
Hi,

First, Henry has a microphone (and so has the camera I believe), so recording sound wouldn't be a problem, but we were told last year that for privacy considerations this wouldn't be allowed. What has changed?

Second, we only record videos at very low framerate because it would be too much data otherwise. We can perfectly increase the framerate, but then we'd also increase the data volume significantly. I don't think you'd need another camera for that. So, the questions would be: How to deal with the masses of data produced, and how you will in the end be able to browse through a Terabyte of video material?

**Comment by denisehe** [comment]
Hi, 
hm no actually we are not allowed to use an additional camera separate from the robot, cause that would mean another dealing with the data commission again. But the camera on the robot (as strange as it sounds is fine).

I remember that we were told that the new camera we mounted last year does not have a microphone (because I remember being astonished about that).

Higher frame rates would be just required for the walking group sessions for enhance the ability of data analysis.

Cheers Denise

**Comment by marc-hanheide** [comment]
Well, the camera wasn't the problem... SOUND recording was, we were told. Changing the framerate "dynamically", so only during the walking group, might prove trickier... but we can discuss, @cdondrup ?

**Comment by denisehe** [comment]
so this camera has soundrecording? which one? the kinect or the additional camera that we mounted on the headframe last year?
i remember that i was told it has not....

yes for WG only would be enough, even if it can be switched mannually somehow

**Comment by marc-hanheide** [comment]
Both, camera and ASUS have microphones:
![image](https://cloud.githubusercontent.com/assets/1153084/13782835/169f1cc4-eac9-11e5-9b93-c4783d8ce627.png)

But we are not recording because we were not allowed to!

**Comment by denisehe** [comment]
Good Morning, 

well really strange...cause I assumed that the robot had just loudspeakers but no microphones (if i would have been aware, i would not have asked for a new camera actually) - and I was told last year when installing the new cam that was mounted on the frame, that there is just motion but no sound available.

i talked to tobias, he searched through his mails, I also checked mine, it was the issue to not have an additional camera...hhhmmmm. i dont know. maybe it was a misunderstanding on both sides?

but anyways: would it be possible to have sound recordings during the walking groups? 

cheers Denise & sorry for the inconvenience!

**Comment by TobKoer** [comment]
@marc-hanheide @denisehe 
Hi there,

I honestly cannot remember what the sound recording issue was, either some personal reservation from my side or – which is more likely – an objection of the therapists involved.
In general, if the camera also records sound there is no real ban (from the data protection commission), given the camera is part of the robot and data is needed for scientific purposes ;-)

One question could be the amount of data, which I cannot really comment on.  
Another issue, of course is to only switch on the microphone during the walking groups and not in general. Then again we also have to bear in mind that there is a no-video-data policy in the ambulance area.

Cheers,
Tobias.

**Comment by cdondrup** [comment]
Regarding technical issues of increasing the frame rate and recording sound during walking group, if I remember correctly, the camera nodes are started via the launch server. It should therefore be no problem to stop them before the walking group, start them with less throttle, and stop and relaunch the old ones after the group. This means scheduling a stop recording task before each group and a start after or incorporating a call to the correct action server into the walking group task. 

The only detriment, it makes the whole system more brittle as there is an increased chance that the recording is not started correctly afterwards or before the group. As far as I know, there is no way to dynamically change the throttle rate, or is there @marc-hanheide ?

**Comment by marc-hanheide** [comment]
I uploaded a test video from the interaction camera, just to make sure you see what you need in it: https://lcas.lincoln.ac.uk/owncloud/index.php/s/rhxCUVTz3tpudIu

I found it looks a bit too much down, but you're the bosses here @denisehe and @TobKoer 

Synchronised Audio is indeed not easy to obtain... I've considered many different options and neither is easily implemented, or, only with regression to the rest of the system. So, only viable option would be to record both audio and video from this camera via VLC, but then we can't stream it to ROS anymore...

**Comment by denisehe** [comment]
Hi @marc-hanheide,
my feedback:
1. the information that the bellbot can be called from the reception is still in but as far as i know not available in this form
2. I would replace the phrase "effektiv einsetzten im HB" - rather I would say "soll herausgefunden werden, in welchen Bereichen der Roboter eine Unterstützung sein könnte" 
3. In the end a short final sequence would be nice, eighter the robot driving off and seen from behind or a close up from its eyes that open and look away ...(but such a scene is already in)
4. the sequence that is marked as "to be eliminated" wasn't that the scene with the bumper?
   I think it would be well worth it to have that sequence but maybe after the sequence where we explain that the robot tries at its best to avoid obstcles - and then insert this scene - in case it does not work there is this bumper as a last savety - that it does not hurt and will stop immideately.

:-)

**Comment by marc-hanheide** [comment]
This was meant to go to #290, right? Looks a bit off topic here...

**Comment by denisehe** [comment]
interaction camera: 
yes it is too low, there was a man visible, but I could just see his chest and legs

**Comment by marc-hanheide** [comment]
Up to you to adjust it!

**Comment by denisehe** [comment]
hehe, yes of course ^^

**Comment by marc-hanheide** [comment]
as stated on https://gitter.im/strands-project/aaf_deployment I now show the interaction cam on the robot, so you can adjust

**Comment by denisehe** [comment]
oh sorry - i was out of the office

**Comment by denisehe** [comment]
ah @marc-hanheide i just remembered: didnt we adjust the interaction cam to the hight of sitting persons as we said that the headcam will capture all the rest?
I checked the cam and saw that we rally fixed it in this way...

**Comment by marc-hanheide** [comment]
As long as you are happy, I shall be happy, too.
