### ISSUE TITLE
Expert interventions

### ISSUE THREAD

**Issue by hawesie** [strands-project/aaf_deployment#311]
As in previous years, please remember to log expert interventions so we can evaluate system performance.

**Comment by marc-hanheide** [comment]
yes, @Jailander said he start[s/ed] a log somewhere.

**Comment by Jailander** [comment]
Hi yes I have it on my desktop was going to ask if the aaf_deployment wiki would br an appropiate place for it, or dobwe want it private and I'll do it in the strands_management wiki

**Comment by marc-hanheide** [comment]
Look here: https://github.com/strands-project/strands_management/wiki/Y2-Care-Deployment-Logs That was last year. Don't put it in the public Wiki, please.

**Comment by Jailander** [comment]
exactly why I didn't make it public ;) will add a page for this year on this style and paste my log on it

**Comment by Jailander** [comment]
https://github.com/strands-project/strands_management/wiki/Y3-Care-Deployment-Logs

**Comment by TobKoer** [comment]
This all looks good - it's only we are in 2016 now ;-)

**Comment by Jailander** [comment]
oops, copy paste problems, fixed
