### ISSUE TITLE
AAF deployment waypoints

### ISSUE THREAD

**Issue by TobKoer** [strands-project/aaf_deployment#314]
@Jailander, @marc-hanheide, @cdondrup, @denisehe   

Unfortunately we need to change waypoints (or change them back to the Y2 status). 
The robot is blocking beds and patient transfers in the 'main corridor' (i.e. the waypoints "Frisoer", cafeteria and the lifts). 
People pushing beds can barely squeeze past the robot when it does infoterminal there. In case of an emergency transport or patients in pain, this can become a major issue. Transfer of patients overrules everything happening in the care hospital, so that also does not leave room for experimentations or asking staff for 'tolerance', even at the cost of robot navigation.

**Comment by Jailander** [comment]
Can I ask you for some pictures of the current status (the robot on the waypoint now) and maybe pictures of where youd like them moved

**Comment by denisehe** [comment]
hi. can we not just shift the waypoint 40cm further wowards the wall or move the waypoint to the point where the robot stoped for walking group last year...I think we talked about that during the pilot!

**Comment by Jailander** [comment]
And we tested it, we can do it but we would need someone there to test if the robot can safely anvigate there

**Comment by denisehe** [comment]
ok so how should we do that now? :-)
how can i support?
