### ISSUE TITLE
battery warning email

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#318]
Can I ask @gestom or @Jailander to set up the battery critical email cron job that we have on Linda on Werner as well? Or let me know where I find that script so I can do it?

**Comment by Jailander** [comment]
Will do it, but for future reference its here ;) 
https://github.com/strands-project/strands_utils/tree/hydro-devel/battery_check

**Comment by Jailander** [comment]
this will be sending a few testing emails now
