### ISSUE TITLE
mounting of the magnetic strip

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#32]
@creuther is going to order 20m of magentic strip to be send to AAF (@denisehe). @creuther also recommends to use safety tape ![safety tape](http://www.harborfreight.com/media/catalog/product/cache/1/image/9df78eab33525d08d6e5fb8d27136e95/i/m/image_16543.jpg)

**Comment by denisehe** [comment]
I just ordered 30m of magnetic strip!

**Comment by marc-hanheide** [comment]
:+1:

**Comment by denisehe** [comment]
magnetic strip arrived!

**Comment by denisehe** [comment]
hey there - the sensor was lowered today. positive news: it is working! breaks hit immediatelly after detecting magnetic strip

A testrun in the buliding showed no false positive detections! :-)

**Comment by marc-hanheide** [comment]
Now, that's a relief! Great, thanks for testing @denisehe and @ToMadoRe ! We shall then use this as our main safety feature.
