### ISSUE TITLE
setting max bumper recoveries parameter

### ISSUE THREAD

**Issue by bfalacerda** [strands-project/aaf_deployment#323]
@marc-hanheide as you asked, here's some info about setting the max number of tries for bumper recovery.

To set it at runtime to a value k, you need to do `rosparam set /monitored_navigation/recover_states/recover_bumper "[true, k]"`

(The first value in the  pair is used to deactivate the behaviour altogether)

To have it from startup, you'll need to merge:

https://github.com/strands-project/strands_navigation/pull/300
https://github.com/strands-project/strands_systems/pull/119
https://github.com/strands-project/strands_recovery_behaviours/pull/56

and add `max_bumper_recoveries:=k` as an argument to `strands_navigation.launch`.

@Jailander I noticed topological navigation keeps trying the same goal forever, even when the bumper recovery outputs, so atm these PRs won't change the robot's behaviour. Any idea why that happens?

**Comment by Jailander** [comment]
Hi no idea, I didn't notice this, I'll take a look and try it on Linda thank you for telling me

**Comment by bfalacerda** [comment]
Here's what it keeps outputting forever (from what I understand this should happen 3 times, but then topo nav execute policy should give up):

```
[INFO] [WallTime: 1458735060.831616] State machine terminating 'bumper_recover':'not_recovered_without_help':'not_recovered_without_help'
[INFO] [WallTime: 1458735060.832904] ABORTED
[INFO] [WallTime: 1458735061.072468] Do move_base to WayPoint10
[INFO] [WallTime: 1458735061.135786] State machine starting in initial state 'MONITORED_NAV' with userdata: 
        ['goal', 'result']
[INFO] [WallTime: 1458735061.136767] Concurrence starting with userdata: 
        ['goal']
[INFO] [WallTime: 1458735061.145035] State machine starting in initial state 'NAVIGATION' with userdata: 
        ['goal', 'n_fails']
[INFO] [WallTime: 1458735061.227903] Concurrent state 'bumper' returned outcome 'invalid' on termination.
[INFO] [WallTime: 1458735061.232531] Concurrent state 'stuck_on_carpet' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1458735061.235825] Concurrent state 'pad_pause_nav' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1458735061.239520] Concurrent state 'magnetic_strip' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1458735061.242152] Concurrent state 'service_pause_nav' returned outcome 'preempted' on termination.
[ INFO] [1458735061.258481604]: Got new plan
[INFO] [WallTime: 1458735061.358819] State machine terminating 'NAVIGATION':'preempted':'preempted'
[INFO] [WallTime: 1458735061.359977] Concurrent state 'NAV_SM' returned outcome 'preempted' on termination.
[INFO] [WallTime: 1458735061.377262] Concurrent Outcomes: {'stuck_on_carpet': 'preempted', 'magnetic_strip': 'preempted', 'service_pause_nav': 'preempted', 'bumper': 'invalid', 'pad_pause_nav': 'preempted', 'NAV_SM': 'preempted'}
[INFO] [WallTime: 1458735061.378168] State machine transitioning 'MONITORED_NAV':'bumper_fail'-->'bumper_recover'
[INFO] [WallTime: 1458735061.380202] State machine starting in initial state 'BUMPER_HELP' with userdata: 
        []
[INFO] [WallTime: 1458735068.440629] State machine terminating 'BUMPER_HELP':'not_recovered_without_help':'not_recovered_without_help'
[INFO] [WallTime: 1458735068.441395] State machine terminating 'bumper_recover':'not_recovered_without_help':'not_recovered_without_help'
[INFO] [WallTime: 1458735068.442738] ABORTED
[INFO] [WallTime: 1458735068.670396] Do move_base to WayPoint10
```

**Comment by Jailander** [comment]
yes this should only happen three times, I have seen topological navigation quitting in werner so there should be a special case. I'll be on it as soon as possible. thanks!

**Comment by marc-hanheide** [comment]
I'm lost with this, can @bfalacerda and @Jailander update me if this is still relevant?

**Comment by bfalacerda** [comment]
depends on if you want a max number of bumper recovery attempts. I don't remember why you wanted it, but I don't see the point of stopping the recover bumper behaviour
