### ISSUE TITLE
name the waypoints the bellbot should go to

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#33]
name the final destinations and the final waypoint the robot can go to.

@Jailander please put a screen shot of the topop map here, @denisehe to give names for the places, @yianni to see.

**Comment by denisehe** [comment]
hey there I have got the list with rooms. 
unfortunatelly I can not upload the map of the house that comes with it.
I will send the documents streight to marc, maybe he can upload them from his backend.

**Comment by Jailander** [comment]
Hi, can you send them to me? I will create the topological map from them

**Comment by denisehe** [comment]
in a sec ;-)
