### ISSUE TITLE
[aaf_walking_group] Use new media_server to retrieve file from datacentre

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#34]
This applies to: 
- [x] All the music playing nodes @nilsbore 
- [x] The entertainment interface for images and videos @creuther

**Comment by nilsbore** [comment]
Alright, I'll finish this and the managed player integration today.

**Comment by denisehe** [comment]
Hey, I am not sure if it really fits here - but as it concerns the walking group, I add it here:

We agreed that Henry should play different sounds at different areas when walking around the building.
How is this feature implemented:

Should we assign certain areas, that you then point out for the robotic system as "predefined areas"?

And how is the sound fed in:
eigther: in this predefined areas predefined sounds are played
or: we have the backend to fill the predefined areas with sounds on or own?

**Comment by nilsbore** [comment]
Hi Denise,

to begin with, the entertainment interface. You use the web interface that @cburbridge developed, simply put all the songs you want to be played in a `music_player` collection of media in that interface.

For the music, you put all the songs in a collection in the same interface, the default one right now is `aaf_waypoint_sounds` so maybe choose that for simplicity. Then we associate each of the songs that you put in there with places in the map where you want them played. This is the "waypoints" that we've defined for Henry, the points that he knows how to get to. So for example, we can associate "WayPoint4" with the file name "cowbells.mp3". Maybe we can send you a map picture with the places and names of the waypoints and you can tell us at what waypoints you want certain sounds played?

Finally, there are the sounds that are played when Henry's navigation fails during the walking group. Just put these in in a `walking_group_recovery` collection in the web interface.

**Comment by denisehe** [comment]
okay but how can we tell him that he should play the song during driving along thus, in between waypoints - not just when shortly stoping at the waypoint?

**Comment by cdondrup** [comment]
You can't, we have to use a waypoint for this. However, the robot should not stop at intermediate waypoints, meaning it only stops at the goal even if it passes through other points that have music associated with them.

**Comment by cdondrup** [comment]
Does anyone have time to look at this for the entertainment interface? If @creuther has time to do that, that'd be great but since he is usually pretty busy and you have done that for the music bit already, could you have a look as well @nilsbore?
If not, I'll try to get it to work.

**Comment by cdondrup** [comment]
Video is also working now: https://github.com/strands-project/strands_ui/pull/91
Done.
