### ISSUE TITLE
Walking group - publish to topic when walking group is over

### ISSUE THREAD

**Issue by Jailander** [strands-project/aaf_deployment#340]
This is related to this issue:

https://github.com/strands-project/strands_navigation/issues/249 

but also would it be possible to publish something to: `aaf_walking_group/resting_node` when the walking group is over to avoid this problem for now?

**Comment by marc-hanheide** [comment]
what is this about? What shall it address? Is it something we need to think about for Yr4?

**Comment by Jailander** [comment]
I think @cdondrup already fixed this, @cdondrup can you comment?

**Comment by cdondrup** [comment]
I remember that I wanted to do this, yes... I don't I have though.
