### ISSUE TITLE
Walking Group - yesterdays failures

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#341]
Hi @cdondrup :-)

I just wanted to comment on one issue that occured throughout the whole session yesterday: at the predefined waiting points the screen always showed "waiting for therapist" instead of the regular "weiter" icon.
Sometimes this happened before but the screen changed very quickly to the "weiter" icon. Yesterday though the "waiting for therapist" icon remained there quite some time, thus the therapists were confused, holding up their cards => thus the robot started processing agin and after again some while (of corse) the admin interface appeared

well do you know why this "waiting" icon appeas at these points or why it stayed ther so long and not just the weiter button

I guess all the other failures were due to persons in the corridors who did not step out of the robots way, even when it was struggeling a lot (thus a behavior you for sure would not encounter amongst human beeings ;-) )

**Comment by marc-hanheide** [comment]
@cdondrup is there something that needs to be done? Otherwise, please close as appropriate.

**Comment by cdondrup** [comment]
This happens once in a while but I have no idea why. The mysteries of smach...
