### ISSUE TITLE
Human-Aware navigation

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#352]
As it is agreed, we want to use the new human-aware navigation of @cdondrup at AAF. Here are the things I believe are relevant:
- [ ] make sure it works with wheelchair detector of @Pandoro 
- [ ] design an experiment around this, e.g. flip the behaviour every week? To be discussed with @cdondrup

**Comment by marc-hanheide** [comment]
@cdondrup and @marc-hanheide to discuss how this could lead to a publication.

**Comment by cdondrup** [comment]
See: https://github.com/strands-project/strands_perception_people/issues/209 regarding wheelchairs.

**Comment by marc-hanheide** [comment]
Jobs to do:
- [ ] write dispatcher for human-aware actions
- [ ] start off with it defaulting to the old behaviour
- [ ] implement human-aware nav from the models

**Comment by cdondrup** [comment]
@Jailander is it still required that every action that is triggered on an edge has a dynamic reconfigure that mimics move_base? Like this atrocity: https://github.com/strands-project/strands_hri/blob/hydro-devel/strands_human_aware_navigation/src/dwa_dyn.cpp

Because then the action dispatcher would need that as well.

**Comment by Jailander** [comment]
Hi yes I am afraid that we still need that atrocity we both designed for every action based on move base, if you have an independent action server that will handle the navigation (such as door_pass) then that is not necessary

**Comment by cdondrup** [comment]
I'm glad you want to take the fall for my terrible C++ skills ;P
I'll make sure to copy this over to the dispatcher then.

**Comment by Jailander** [comment]
haha I don't want to steal your credit, just saying that I am quite comfortable with this solution to my own shame :p
