### ISSUE TITLE
get Henry to AAF

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#353]
- Can we aim to get the robot to AAF in the first week of Nov (e.g. 1/11/16).
- @capamat-aaf to boot up laptop and connect to network.

**Comment by mzillich** [comment]
Yes, that's ok.

**Comment by capamat-aaf** [comment]
Laptop is booted. It has to run 24/7, correct?

**Comment by cdondrup** [comment]
The laptop is our gateway to inspect the robot remotely and make regular backups of the collected data so it has to run 24/7, yes.

**Comment by capamat-aaf** [comment]
The first of November is a holiday and I'm waiting for an ok to get the second off too.
@mzillich would the 3rd or 4th work?

**Comment by mzillich** [comment]
4th is ok for me

**Comment by capamat-aaf** [comment]
Brilliant, then please let me know, if you need anything from me :)

**Comment by kirumang** [comment]
The robot arrived at AAF now, and connected to network.
@marc-hanheide please check the network now. 
I guess I need to turn the robot off after checking the network

**Comment by marc-hanheide** [comment]
I'll check it next thing. But please keep everything up and running even when you leave.

**Comment by marc-hanheide** [comment]
Please be online at 
https://gitter.im/strands-project/aaf_deployment
