### ISSUE TITLE
Cognitive Game

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#356]
@capamat-aaf to check for test license, and to see if this should be a specific extra task to schedule for the robot. Also to see if there is a gain.

**Comment by marc-hanheide** [comment]
facilitated by therapist

issues:
- [ ] internet connection needed
- [ ] license needed

**Comment by capamat-aaf** [comment]
Bad news: the people from RehaCom answered; the software has to be installed locally, the only thing that happens over the internet is the licensing, whatever that means. 

They also sent me a link to a demo version, which I cannot open at the office.
Opening the link with the phone sent me to a download site where it say: "RehaCom available only for Microsoft Windows". 
So I guess that resolves it then :(

**Comment by marc-hanheide** [comment]
yep... what a great product ;-) Well, I think that's a no. Just confirming with @hawesie: No Cognitive Games on the robot at AAF, it seems.

**Comment by hawesie** [comment]
Ok, not a lot we can do then.
