### ISSUE TITLE
new reading zone

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#359]
some waypoints need to be moved due to new reading zone at "Feuerloescher".

@capamat-aaf to put a photo.

Marc

**Comment by capamat-aaf** [comment]
![tmp_3913-img_20160919_15111191255575038](https://cloud.githubusercontent.com/assets/21201058/19185796/7ab31c36-8c83-11e6-93c3-0afbdf46a85a.jpg)
![tmp_3913-img_20160919_1511000-392483734](https://cloud.githubusercontent.com/assets/21201058/19185805/85607778-8c83-11e6-84ac-f88f9fecb8cd.jpg)

I will take some better ones and of the metallic threshold as well.

**Comment by capamat-aaf** [comment]
Here are new photos, let me know if you need more.
![img_20161010_0833180](https://cloud.githubusercontent.com/assets/21201058/19229565/cc686462-8ece-11e6-888f-11d3a199148f.jpg)
![img_20161010_0833285](https://cloud.githubusercontent.com/assets/21201058/19229741/292d8a32-8ed0-11e6-8602-7849f886ffb7.jpg)
![img_20161010_0832570](https://cloud.githubusercontent.com/assets/21201058/19229740/29279000-8ed0-11e6-9f0d-88b39f71c0ec.jpg)
![img_20161010_0833131](https://cloud.githubusercontent.com/assets/21201058/19229743/294e4bc8-8ed0-11e6-8945-56fb23163c4a.jpg)
![img_20161010_0833494](https://cloud.githubusercontent.com/assets/21201058/19229842/d6fb8074-8ed0-11e6-8955-d6f78f33aca5.jpg)

**Comment by marc-hanheide** [comment]
Thanks
