### ISSUE TITLE
Interface Henry - feedback & open questions

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#36]
• Eventually the blue text has not enough contrast (we can test that during the pilot trial)
• Lunch Menu should look a bit nicer, not just white with plain text but like different background  
         colors for soups, mains, and deserts, it would also be cool if we can have our carrot symbol 
          next to the vegetarian dish. So that this carrot symbol is fixed next to or on the side of one 
          entry space.
• Picture gallery, back & forth buttons can be a bit smaller and picture bigger => otherwise details 
        in the pictures won’t be visible
• News ticker => text partly overlaps with pictures
• Within the “news” we have daily news as well as house-intern news – there fore the menue has 
         to be subdevided
• Weather icons should be less blurred on the edges
• Also weather forecast for the next days would be good

QUESTIONS: 
When Henry is patrolling – he will show a picture gallery (pictures changing after a while) - Is it possible, via our back-end to change that e.g. if an event has to be announced, to have a “flyer” for this event covering the screen – maybe with the button – for more infos click here – and then more infos about the event pop up on the screen?

Could we subdivide the Icon – “Pictures” 
Call the icon “enterntaiment” or someth like that and have in there 1. Pictures 2. Quizzes about the 140 year anniversary of the house

**Comment by marc-hanheide** [comment]
What specifically did you test and had a look at. Interface on the robot? Or the website I ran?

For the additional features you ask: While this is technically all possible, but we must be a bit careful with the efforts we commit to. Each of these "nice to have features" need to be probably working and tested, and someone will have to dedicate time to actually implement them. So, I want to ask you @denisehe to think what is really needed and helps us answering relevant questions, and what is just "nice to have". I feel neither the quizzes nor the "flyer" are crucial, are they?

**Comment by denisehe** [comment]
hey marc, 

yes sure - I understand your point. maybe we can find an easy going solution - as I think it is important to provide a good information offer so that ACC is enhanced.

what about:
1. if there are upcoming events, we can just create a announcment-flyer that we feed in from the back end so that henry is showing it during patroling - on this day instead of the random picture galery that is shown during patrol.
2. how easy is it to develop a quiz front-end for approx. 10 questions?

**Comment by marc-hanheide** [comment]
Implementing a quiz in our own framework is quite a job. I expect someone experienced could do it in two days. But then this person wouldn't do the other bits. We need to prioritise and you need to convince me that this is needed. If you find a web site that you can use to design quizzes and run them, then we _could_ integrate that website. But it would have a very different look and feel than the rest of the system. So. A bit like displaying the ORF page etc would be which is why we decided not to do that but integrate the news feed instead. Why would we need the quiz? @hawesie, what's your view?

**Comment by marc-hanheide** [comment]
For the flyer. You can perfectly upload any image and assign it to the set of images that is displayed when Henry moves. If it's the only image assigned then it would be displayed all the time.

**Comment by MartinDesigner** [comment]
Try Createer.com. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned template (look here https://beta2.createer.com/Templates) s and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
