### ISSUE TITLE
[info-terminal] Info-Terminal Routine

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#37]
- [ ] define a subset of waypoints to be used for info-terminal (@Jailander with @gestom)
- [ ] implement a routine that submits task for the next _n_ minutes (or max _m_ tasks)
- [ ] run with charging level being configurable

**Comment by denisehe** [comment]
do you need any information where it would be nice to have waypoints from our point of view ?

**Comment by marc-hanheide** [comment]
That would be useful... But best if @Jailander would send out a tpoplogical map that you then annotate!

**Comment by Jailander** [comment]
@denisehe I can send you the topological map, but I'm afraid it would be less practical for you as it looks like this:
![rviz_screenshot_2015_03_18-12_51_54](https://cloud.githubusercontent.com/assets/5035967/6712026/5eec61cc-cd82-11e4-896e-f8e564a5a474.png)

Or I would need to spend some time writing something that renders the map nicer (which I will at some point).
So why don't you annotate these places on the map you sent me with the bellbot nodes:

![bellbot_plan-3](https://cloud.githubusercontent.com/assets/5035967/6712078/a0503076-cd82-11e4-8edb-09c39a914818.png)

and I'll add those too or use the nodes we have there if we already have them.

**Comment by Jailander** [comment]
@marc-hanheide for defining the set of nodes for the info terminal we are going to add "tags" (e.g. Info terminal) in the meta information of the nodes, and I am going to implement a service that returns the list of nodes an specific "tag" on them and of course another service to add tags to nodes.

**Comment by Jailander** [comment]
This was agreed with @gestom

**Comment by marc-hanheide** [comment]
ok

**Comment by Jailander** [comment]
Are you happy with this? or should we plan for something different?

**Comment by marc-hanheide** [comment]
I don't have enough knowledge to really comment. If you agreed it go for it.

**Comment by denisehe** [comment]
Hey thanks @Jailander I will use our map and annotate zones - I will also try to take your red marked waypoints in your map into account - I guess it should be overlapping, or the zones should be inbetween nodes that are already existing? Am I right?

**Comment by denisehe** [comment]
ah no, I mixed up the task - we are in the discussion about waypoints for the infoterminal here! I thought its about marking zones where the robot should play musik during the waling group

okay so I will just mark points where the infoterminal should be displayed and on what time of the day!

**Comment by Jailander** [comment]
Hi, don't worry about  thhe previous way points put points or areas that you think are relevant and I'll take car of making the map. Also if you want make comments on what things should happen where and I'll liase with the Different tasks

**Comment by marc-hanheide** [comment]
OK, so we need some progress on the routine. Here's what I believe needs to be done:
- [x] The [GoToPerson](https://github.com/strands-project/aaf_deployment/blob/indigo-devel/info_terminal/approach_person_of_interest/action/GoToPerson.action) action should be simplified, as we don't have a pose to turn towards (no waving detection available), and `go_to_person` is not needed. All code that uses the service should be amended accordingly (see below).
- [ ] infremen needs to be configurable (via a service?) to be turned on and off, to avoid spamming the executor with requests when we don't want to run this (we of course want to run it almost all the time, but not during the night, for instance). It must also not call the `/task_executor/set_execution_status` service as it is not the only component to decide if we are executing. Hence, it should not call it at all. 
- [ ] infremen's models need to be persistent (using message_store) so that it doesn't start from scratch, @gestom is it already or are you working on it?
- [ ] infremen should not submit a [dummy_pose](https://github.com/strands-project/aaf_deployment/blob/indigo-devel/info_terminal/infremen/src/infremen.cpp#L211)
- [ ] infremen should not use the social card reader
- [x] the current [approach_person_of_interest](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/info_terminal/approach_person_of_interest) should be refactored to be based on [AbstractTaskServer](https://github.com/strands-project/strands_executive/blob/hydro-release/strands_executive_msgs/src/strands_executive_msgs/abstract_task_server.py), so that a factory service for tasks (`..._create`) is available. 
- [ ] then infremen should use that factory service to instantiate the `Task` object, to make sure its fields are properly instantiated
- [x]  [approach_person_of_interest](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/info_terminal/approach_person_of_interest) needs to be modified so it doesn't use a `Pose` to turn towards, as we don't have waving detection. Instead, it should just run at the waypoint, make the head and PTU turn towards the screen, and enable [strands_gazing](https://github.com/strands-project/strands_hri/tree/hydro-devel/strands_gazing) rather than approaching a person
- [ ] #42 and #29 still need implementing

Can I invite @cdondrup @Jailander @nilsbore @cburbridge and @gestom to discuss this with me.

**Comment by gestom** [comment]
Since there is no waving detection, we can completely remove the person approaching part. I can do the 'strands-gazing' and PTU movements in the infremen.

**Comment by cdondrup** [comment]
For the PTU and gaze I have some code that you can just use: https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_walking_group/src/aaf_walking_group/utils.py#L11-L50

Can either do the same in C++ or just use the python file by importing it from the walking group.
The rest sounds sensible to me.

**Comment by marc-hanheide** [comment]
@gestom I don't think you can do it in `infremen` as `infremen` doesn't implement the _task_, but the _routine_ (i.e. the component that submits tasks to the scheduler). That means the task server (currently called `approach_person_of_interest`, but should probably be renamed) will have to do that. I suggest we keep these things nicely separated. infremen suggests task (with a simplified interface) to the scheduler, and then there is a task server that implements the actual task.

**Comment by marc-hanheide** [comment]
I'll come and see the Lincoln people in a few minutes to discuss this in person

**Comment by marc-hanheide** [comment]
I suppose this is done @gestom ?

**Comment by gestom** [comment]
With a few exceptions: 
1) /task_executor/set_execution_status service is still called (this was needed for testing)
2) Was working quite OK with task_executor_top, but seems to have issues with task_executor_mdp.

**Comment by marc-hanheide** [comment]
OK, cool. The /task_executor/set_execution_status can also be called manually via `rosservice call /task_executor/set_execution_status '{status: true}'` 
The MDP one is interesting. It shouldn't have any effect with that, should it?

**Comment by hawesie** [comment]
No, it shouldn't. In https://github.com/strands-project/strands_executive/issues/173 we're waiting to see more output to see what's going on.
