### ISSUE TITLE
Back Ends & Admin Interfaces

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#38]
Hey @marc-hanheide, @cdondrup, @cdondrup, @Jailander, @nilsbore, @yiannim - probably it is already existing but I did not find it - I would need a description of the admin interfaces - so what exactly you implemented by now, for which tasks and whom it therefore concerns!

Thanks, Denise

**Comment by cdondrup** [comment]
Being linked twice, I feel very responsible now :)
I think the second one should have been @cburbridge 
I will write something about the interfaces for the deliverables and can share that with you.

**Comment by denisehe** [comment]
yes you are right, sorry about that - I really did not meen to throw all the preassure upon you now :-D
