### ISSUE TITLE
Infrastructure changes at AAF Y4

### ISSUE THREAD

**Issue by capamat-aaf** [strands-project/aaf_deployment#381]
I picked up a conversation that is unfortunately harrowing news.
The area where the robot charging station is, will become a "lounge area" with a carpet and a small couch.
These changes are going to happen in the third week of January.
I drew some pictures to show the exact location.
![2](https://cloud.githubusercontent.com/assets/21201058/20620324/759837da-b2f9-11e6-9d16-c4d62cc6b433.png)
![4](https://cloud.githubusercontent.com/assets/21201058/20620330/79a1af32-b2f9-11e6-86f4-8818abff194e.jpg)

One of those septums will be moved as well.
The carpet is the same as the one close to the fire extinguisher
![img_20161124_1540358](https://cloud.githubusercontent.com/assets/21201058/20620380/bb257182-b2f9-11e6-8bd7-1d7d1705f951.jpg)

These changes are inevitable. I thought of two spots where the charging station could be moved, one would be a bit to the right from where he is now, if he can drive on the carpet. The other one would be on the other side of the reception desk. 
![3](https://cloud.githubusercontent.com/assets/21201058/20620725/5dcebee2-b2fb-11e6-9e7c-5485362f883b.png)

This will be a huge effort regarding moving all the necessary WayPoints and I assume changes in the topography as well.
I don't know, if I can have any influence on this, but if you guys tell me that moving the charging station etc won't be possible to do, I'll demand a postponement.

And there will be some painters coming again, I'm trying to find out the exact dates...

**Comment by Jailander** [comment]
WOW, that is bad news :confused: honestly any waypoint but the Charging station would be less problematic. The main problem right now is that the Charging Point is our 0,0 in the map. Also with changes in topology midway the deployment I am not sure how well our prediction system will work (not too well I'd say), and how this will affect the infoterminal experiments (@gestom can have a more clear opinion on this, but I guess it won't be too happy).
On the other hand, it is not impossible we would need remapping and moving the WayPoints only. If it was absolutely necessary.

**Comment by cdondrup** [comment]
Don't the security guys have two charging stations? Could we just add the new location as charging station 2 and never use 1?

**Comment by gestom** [comment]
Good to know in advance, so we are ready for this. We could add another charging station without significant problems and not starting from 0,0 should not be that problematic either. The predicttions will be affected, but on the other hand, we have a chance to observe a structural change and see how the persistence part of FreMEn deals with it.

**Comment by Jailander** [comment]
we only need to move the Charging station and change the name, but as I said this will affect the infoterminal experiments, and we would definitely not use position injection. Also after restarting the robot in the ChargingPoint we would need to inject the robot pose to Amcl rather than leaving it to 0,0

**Comment by marc-hanheide** [comment]
First of all, thanks @capamat-aaf for the early heads-up. Then, when you say the decorators are coming in, is this also planned for third week of Jan? Or earlier? Finally, I think this is not too bad, rather it's interesting. But we really need to know the precise schedule, including the times when we probably cannot operate at all.

**Comment by capamat-aaf** [comment]
Thank you guys for staying positive! I felt so mad when I found out...

Regarding painters, I will be informed once the exact times are known, it's not going to be any time soon though.

But it's not too bad apparently, they are going to paint only a couple of walls:
• part of the ambulance area
• the one walls on the left of the entry, where the elevator and the bins are
• the niche where it would stop for the walking group, between chapel and tea kitchen.
I'll post the exact times when I know them and I requested for them not to paint the last wall on either Mondays or Thursdays.

**Comment by capamat-aaf** [comment]
@marc-hanheide @Jailander 
Unfortunately, and without a notification of course, they already started working. No carpets or sofas yet, but they are moving the septums. Today. The "entire" day, but I will receive a call when they're done.
The problem is the charging station, I'm completely lost on what to do about this. 
Should I bring it to the AAF office and charge him here, if he requires to? But what can I do when he schedules info-term there?

**Comment by capamat-aaf** [comment]
![img_20161220_1144107](https://cloud.githubusercontent.com/assets/21201058/21347727/2be260e2-c6aa-11e6-9355-a312ee565724.jpg)

They aren't completely done yet, but the septum is going to stay like this.
On a side note, I think I nailed the approx. location in the first post of this issue...

**Comment by marc-hanheide** [comment]
Ok, could you try to find new suitable positions for the station and propose them here with photos, please.

**Comment by capamat-aaf** [comment]
![img_20161220_1400113](https://cloud.githubusercontent.com/assets/21201058/21353482/7d141e6c-c6c6-11e6-84df-429b6556df13.jpg)

**Comment by capamat-aaf** [comment]
![img_20161220_1546266](https://cloud.githubusercontent.com/assets/21201058/21354896/24af8e54-c6cc-11e6-8c99-ae5791cc80c6.jpg)

**Comment by capamat-aaf** [comment]
We have a date for the carpet's arrival.
Next Monday, the 16.01., it is estimated that it will take the entire day.
How do we proceed next?

Additionally, from Tuesday 17th to Thursday 19th workers will modify things inside the cafeteria and they might leave tools and other thing in the hall. I will talk to them on that day and see, if they'll block the entire path and Henry can't pass or not.

**Comment by capamat-aaf** [comment]
There are electricians checking the lights and we were asked for Henry to be careful or not go their way at all.  And supposedly they'll be here the entire week, in different areas of the house.
