### ISSUE TITLE
[bellbot] - szenario description

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#39]
Hey @yianni, how is it going with the bellbot implementation? I just wondered how the bellbot functions are implemented now, or better said which of the possible appraoaches you set into action.

During Winterschool we were talking about if it schould be a presheduled offer, or that the receptionist can call the robot to come.

I somehow missed the decition how this was now implemented?

Cheers Denise

**Comment by denisehe** [comment]
or in general, could I have a short description of how the task is ment to start, run and end exactly?

**Comment by gatsoulis** [comment]
Send you a personal email as it does now allow me here to attach pdfs.

**Comment by denisehe** [comment]
Following your description the user has to choose a certain room type and thereafter a new GUI with a list of rooms appears.

As we have many offices, that would overload the screen I have following suggestion:

Main GUI:
select between

Seminar Rooms 
Person (Name)
Units (Lifts)
"Others" (chapel, hairdresser, cafeteria)

when "person" is selected a keyboard can appear where the user can enter the name - at least it is like this on our trainticket terminals - when entering on the top of the screen an alphabetical list with names appears and the more letters you enter the more the list gets focused until at last the name of interest remains (i hope i could explain that well enough) ;-)

when the other options are selected a list of rooms could occur (as you already suggested in your description)

**Comment by denisehe** [comment]
hi @yianni 
I have a question about the bellbot scenario - how does voice output programming and robot behavior correspond in regard of programming?

e.g. do you have to programm certain time slots when the robot should say something, or can the robot just drive and additionally the voice output can be activated?

**Comment by gatsoulis** [comment]
hi @denisehe 

not sure how the strands robot voice output works and whether it holds the main ROS loop which would prevent it from doing anything else while talking.

**Comment by denisehe** [comment]
@marc-hanheide @hawesie - how does it work? (see question to yianni above  ;-)

**Comment by denisehe** [comment]
@marc-hanheide as far as I can see: looks really nice :+1: 
thanks :-)

**Comment by marc-hanheide** [comment]
For voice output: either is possible easily. Speaking while driving is no problem. Well, no problem besides that it might not be very good as people should concentrate on walking rather than trying to understand the robot...

**Comment by denisehe** [comment]
@yianni could we actually adapt the last evaluation screen feedback options on Henry's bellbot task?

As we are designing this years evaluation we would have 5 questions in total that would be cool if we can ask (answering with pressing smilies is still okay)

it would be:

I am satisfied with the service
It is convenient fo have a bellbot
I would use the bellbot again
I find the bellbot easy to use
Speed question 

Is that possible?

**Comment by gatsoulis** [comment]
I'll see what I can do.

**Comment by denisehe** [comment]
thanks! please do let me know as soon you know more!!
