### ISSUE TITLE
Mass Times

### ISSUE THREAD

**Issue by capamat-aaf** [strands-project/aaf_deployment#390]
Disclaimer, apart from the morning mass I have never seen anything going.
EDIT: Veronika doesn't think that any actions have to be taken

General:
Mass: Tuesday and Friday (Saturday, Sundays, and holidays) 10h30
Communion: Friday 16h30
Rosary: every day 13h30
Way of the cross: Thursday 15h00

Xmas ones (apart from Sat&Sun&usual ones)
22.12. Thursday 10h30
26.12 Monday 10h30
27.12. Tuesday cancelled

WE:
Mass: Saturday, Sundays, and holidays 10h30
Rosary: every day 1st Saturday of the month 15:00
Way of the cross: Sunday 15h00

**Comment by marc-hanheide** [comment]
Good to know... But if Veronika is not too concerned, we leave it for now.
