### ISSUE TITLE
[walking group] - szenario description

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#40]
@cdondrup can I also have a general description of the walking task? explaining how the task starts, how it proceeds and also ends or can be ended if needed. 
And what the therapists have to ware/do etc.

Thanks :-)

**Comment by cdondrup** [comment]
@denisehe Do you need anything besides the document I sent? You can also have a look at the [README](https://github.com/cdondrup/aaf_deployment/blob/recovery/aaf_walking_group/README.md) for a more technical description on how to use the system.

**Comment by denisehe** [comment]
@cdondrup thanks for asking, but you gave a very clear overview of what is planned for the WG! But, I am really very curious to see it in real - and I guess questions will come up then :-)

**Comment by cdondrup** [comment]
OK, I will close this then and we create new ones after the predeployment ;)
