### ISSUE TITLE
[infoterminal] - szenario description

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#41]
hey @mzillich, @cburbridge - please can I  get a short description of the infoterminal task - how it starts, how it proceeds and how it ends.

And how it is now thougth to be embedded within patrolling-behavior?

Thanks :-)

**Comment by marc-hanheide** [comment]
The info terminal task is pretty straight forward. The robot will effectively patrol and go to places where, from past experience, it is likely to be interacted with. It will show the front page of the info terminal at these points and stand there for approx 5 minutes. Then it might choose to go to another waypoint and offer its services there or to stay longer. When people are interacting, Henry will stay until the finish. People will use the touch screen to query specific information. Additionally, while moving about, people can stop Henry by touching the display. He'll then show the info terminal front page as above. info terminal and patrol are thus effectively the same. @mzillich correct me, please.

**Comment by mzillich** [comment]
no correction, that's right. Info terminal is the idle task.

**Comment by hawesie** [comment]
@mzillich et al, please can I urgently have a screenshot of the info terminal for DR 8.2?

**Comment by cburbridge** [comment]
![infoterm](https://cloud.githubusercontent.com/assets/259580/6904697/99922bd0-d71a-11e4-99e4-a4136e07bad7.png)

**Comment by hawesie** [comment]
Thanks!
