### ISSUE TITLE
[info-terminal] news about HdB

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#42]
@denisehe requested to have the news screen split. Showing global news and also local HdB news. The easiest would be if the local news would also be given by a RSS source. @denisehe are these local news already available online?

**Comment by marc-hanheide** [comment]
@mzillich we need someone who takes care of the info-terminal GUIs. It's not a big job, but I can't do it.

**Comment by denisehe** [comment]
the local news will be available as text files, that we need to fill in.

its internal news, vital tipps, environment tipps 
that need to be filled in - so thee sections

**Comment by marc-hanheide** [comment]
How would you fill this? Does it contain picture? On simply way could be to setup a wordpress account for this...

**Comment by mzillich** [comment]
@denisehe How are local news distributed now?

**Comment by denisehe** [comment]
@mzillich Local news are just distributet to employees via mailings or letter - but residents/visitors do not get hold of these information => it would be nice to have this offer for these persons too.

@marc-hanheide I am not familiar with wordpress - what can we do with that - does it offer just plain text or can we also insert pictures, or change color of the text or fonts?

**Comment by denisehe** [comment]
@marc-hanheide @mzillich : and please could I get some information what the backend for the lunch menue will look like and how the front end is planned (I think it would look boring to have just black text on white background - could we also insert our little pictures that go with the menue? )

**Comment by marc-hanheide** [comment]
@denisehe @mzillich @cburbridge I think we should just populate the local news like we populate the ORF news, via RSS feed.

I have created a wordpress blog at https://henrystrands.wordpress.com/ that you @denisehe and others at AAF can post to. I shall send you the login details by email. This page will provide any blog posts as RSS feed at https://henrystrands.wordpress.com/feed/ so we can easily integrate it in our news section. 

I believe this to be the best and easiest way to manage the content.

Opinions? 

Marc

**Comment by mzillich** [comment]
Great! Yes, that's the cleanest solution.

**Comment by denisehe** [comment]
ok great! thanks a lot!
