### ISSUE TITLE
[walking group] - sounds and songs

### ISSUE THREAD

**Issue by denisehe** [strands-project/aaf_deployment#43]
Hey @cdondrup @marc-hanheide @nilsbore 

how is it planned to have the robot playing eighter songs or natural sounds during the walking group procedure?

I can annotate zones on the map of the house where we should be able to fill in nature sounds via our back end

But the question is: how can the therapists enter the menue to tell the robot that he should play a hiking-song during the next part of the walk?

these therapist wishes would also have to be higher in priority, so that if they want to sing something it can be done anywhere and then blocking out nature sounds that would be played in certain zones if nobody wants to sing something.

Please do give me feedback, how this is planned and if you need such a map with marked zones and if it is best to have these zones inbetween waypoints that are already existing in the topological map e.g. for the infoterminal etc. ?
Or can it be random zones, independant of already existing waypoints?
Or do you use your own waypoints for the walking tasks - and should I refere to these?

**Comment by cdondrup** [comment]
We have to use waypoints for the sounds. However, we can insert new ones, so please mark the spots where to play. If this does not coincide with an existing waypoint, we'll add one.
Regarding the hiking songs, from the discussions before and during the winter school we understood that the robot should play music all the time while driving along. It would!d be inherently difficult for the therapists to start the music while the robot is driving about. We could do offer that at resting areas, but that would require us to redesign the interface and add functionality that we did not expect. Nevertheless, we could, if necessary, add a play and pause button to the guide menu which allows to start or stop the music. The priority could be set higher as the waypoint sounds. @ferdianjovan would you be able to add those buttons calling the services for Nils' music played?

But as a general question, why are we not playing music constantly any more?

**Comment by denisehe** [comment]
okay I will mark zones.

:-S oh no! I imagined it like the robot playing nature sounds in pretargeted areas. so thats his standard routine

on waypoints - when he stops therapists then should be able to choos if they want to enter the song list. 
or in case they have enough of singing, to leave the songlist and the robot continues with its nature sounds.

is that possible?

**Comment by cdondrup** [comment]
It would be possible but it depends entirely on @ferdianjovan since he developed the guide interface. Please liaise with @nilsbore on how to use his services. Should be very straight forward.

**Comment by marc-hanheide** [comment]
Hi,

I want to leave one comment, sorry @denisehe :smirk: 

I think we need to be careful about adding more and more tiny things to the todo list. Is this something that is _needed_ in order to make the walking group work properly, or is it a _nice to have_ feature? More importantly, have we got evidence that the therapist(s) (who are our ultimate customers in this task) would need/want it? 
I'm just very reluctant to have the team be distracted by tiny improvements (no doubt that it would be nice). There is the danger we end up with a fancy-music-playing-sounding-good-looking green bin that doesn't move appropriately :smile: 
All I'm saying is: Let's make sure we work with the right priorities: Let's get all tasks working and integrated, before we iteratively make such improvements. Then, again, I'm not the expert, so if it is needed for a successful walking group task, then it deserves higher priority, but please @denisehe think about the priorities of requests, what is nice to have and what you believe is essential.

**Comment by nilsbore** [comment]
@denisehe I don't understand exactly what you want now, was the first part in response to the robot continuously playing music? The robot will play nature sounds or other sounds you provide us with and if you can point out the places in the map where the robot should do so, that would be great. Right now, it always lowers the music and plays nature sounds when it passes by those areas. If there is no music playing it will still play the sounds.

@cdondrup @denisehe The music is activated in the entertainment interface at the resting points. It will continue playing if you do not pause it. Maybe it should start by default at the beginning of the tour, and as you guys suggest, just add a pause/play button in the guiding interface. Or maybe it's just enough to be able to toggle the music at the resting points.

**Comment by cdondrup** [comment]
Actually, atm [it starts playing](https://github.com/strands-project/aaf_deployment/blob/indigo-devel/aaf_walking_group/src/aaf_walking_group/guiding.py#L28-L32) automatically when the guiding starts. As @nilsbore said, that coukld be moved to the guiding interface if @ferdianjovan has time to do it.

**Comment by marc-hanheide** [comment]
I'd say, leave it as it is now if @denisehe doesn't object. We leave this open, but I want a full running prototype first.

**Comment by denisehe** [comment]
hey, 
@marc-hanheide @cdondrup : yes i totally understand your consern - but the thing is that I am not intending to add on things but as it seems there a missunderstanding happended.

From my point of view it was the genuine intention to have the robot playing nature sounds ( @nilsbore ) when moving along, but that the therapists have the chance to interupt that nature sounds rutine (e.g. when the robot stops at waypoints) so that they can choose songs that they can sing - from a song list where we agreed upon that we can feed into the back end.

but that if they dont use the option to choose songs that henry just plays nature sounds.

that was the original intention.  

I am sorry if that was not entirely clear :-/

**Comment by ferdianjovan** [comment]
I will try to do that on weekend along with https://github.com/strands-project/aaf_deployment/issues/9 if that was the original intention.

**Comment by nilsbore** [comment]
@ferdianjovan Should I implement a service to enable/disable the waypoint sounds?

**Comment by cdondrup** [comment]
Can't we just use the priorities provided by the pygame player?

**Comment by nilsbore** [comment]
That would be nice, didn't know that you could configure that from the outside. Is that possible @marc-hanheide ?

**Comment by marc-hanheide** [comment]
Well, you could simply assign  a low-prio volume of 0 to the nature sounds and make sure its priority is lower than the other things you want to play. Then it would be muted whenever other stuff plays. Is that enough?

**Comment by nilsbore** [comment]
You mean within the waypoint sounds node, not by the webpage calling a service in the pygame player? I think I might as well pause the playing then.

**Comment by marc-hanheide** [comment]
All I mean: Have it play the nature sound, say with priority 0.3, and have it play music files on request with higher priority. Check https://github.com/strands-project/strands_ui/blob/hydro-devel/pygame_managed_player/src/pygame_managed_player/pygame_player.py#L42 The set the `min_vol` for the nature sounds to 0 to disable it whenever something else, e.g. the music, is playing.

**Comment by nilsbore** [comment]
Ok, understood! I guess that more or less solves it.

**Comment by denisehe** [comment]
thanks for adapting the system !!!! :-)

**Comment by cdondrup** [comment]
Closed via #66
