### ISSUE TITLE
[aaf_waypoint_sounds] Warp into action server

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#45]
Currently, as soon as it runs, it will play sounds at the waypoints. This is not really what we want to do. We need to be able to turn it off and on, to not annoy people.

I could also live with a service to pause and resume, but I'd prefer an action server.

**Comment by nilsbore** [comment]
I think we might as well use a server for this, then we can use it in the webpage also if necessary. Sounds ok?

**Comment by cdondrup** [comment]
As I said, if we can turn it off and on, I don't really mind how ;) What ever you think is better. The point with the webpage might actually be a valid argument for a service.
