### ISSUE TITLE
[aaf_walking_group] position of card node improvements

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#49]
The spammy output should be moved to debug level to not hide the statemachine output.

There was talk about making the division into the QSRs "near" an "far" a bit cleverer than it is now, maybe even implementing some simple learning algorithm. I can't remember exactly but maybe @PDuckworth want's to have a look. If no improvements can be made before the feature freeze, please let me know and take care of the outputs.

**Comment by cdondrup** [comment]
Apparently, I was too tired yesterday. It does only spam if set to verbose. Maybe just switching all of the prints and infos to debug level using `rospy.logdebug()` would be the better choice. Still please let me know if there will be improvements. Otherwise, I'll assume this is its final form.

**Comment by cdondrup** [comment]
I guess there won't be anything happening then?! @PDuckworth

**Comment by cdondrup** [comment]
@PDuckworth, I know you are most likely busy with the g4s deployment, but no answer at all is very disappointing I have to say.
I guess there will be nothing happening then...

**Comment by PDuckworth** [comment]
@cdondrup Argh sorry! I totally missed this issue! 

I am fairly busy with the security deployment system. I am also not sure what update you require. This node is just a subscriber/publisher, and just converts a quantitative distance into a qualitative relation "near" or "far".
