### ISSUE TITLE
[aaf_walking_group] Create component that plays jingles from a music collection

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#52]
This shall be called when specific buttons are pressed, e.g. the continue during the tour. I know you probably already hate me for this, but @nilsbore you are my goto guy when it comes to playing sounds now. If you have time to implement something like that, that would be great. It should be able to play different mp3s via a service call, identifying them by name or a list index.
If you don't have time, and please be honest, I'll try to do it or we leave it for now.

**Comment by nilsbore** [comment]
I think this might as well go in `strands_ui`, no? It's pretty general and might be needed for other webpages.

**Comment by cdondrup** [comment]
It could be a general component that takes a music collection and is able to either play them continuously, or one by one identified by their name. Maybe the existing node could be extended? But I am happy with everything that works ;)
strands_ui sounds fine.

**Comment by nilsbore** [comment]
I think it's better with a new one, it's easier and with @marc-hanheide 's player it's really easy to get them to play well together.
