### ISSUE TITLE
[aaf_waypoint_sounds] make aaf_waypoint_sounds package depend on pygame_managed_player

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#6]
This should be using https://github.com/strands-project/strands_ui/tree/hydro-devel/pygame_managed_player for its playing

**Comment by cdondrup** [comment]
Please remember to check the install targets as well: https://github.com/strands-project/strands_ui/pull/66#issuecomment-74734392

**Comment by marc-hanheide** [comment]
Isn't this done by now?

**Comment by nilsbore** [comment]
No, I will sink my teeth into this after the IROS deadline.

**Comment by marc-hanheide** [comment]
Sorry, was confused with all the audio packages that are about. Thanks, @nilsbore

**Comment by cdondrup** [comment]
This is done now.
