### ISSUE TITLE
safety zones

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#61]
In last years deployment, we needed safety zones for Henry to go in the event of an emergency. I presumed we need this again, but then again we need @denisehe to tell us where those zones would be and mark them on the topological map @Jailander provided. Please @denisehe bear in mind that there should be numerous of those more or less safe waypoints, as we want Henry to reach the nearest quickly. Here is how I believe we deal with this issue.
1. The staff interface (available to the reception people and in Denise' office and whereever else you decide you want it) already features a "notstopp" button:
   ![screen shot 2015-03-26 at 14 00 02](https://cloud.githubusercontent.com/assets/1153084/6847775/d873a53e-d3c0-11e4-987c-b9064fb358b2.png) 
   This button shall be pressed by staff in case they want the robot to be out of the way. This is not only cases of fire or similar disasters, but also in case, e.g. the emergency services are coming in to deal with a resident and you don't want a robot to get in their way.
2. A confirmation dialog pops up for staff to confirm they want to activate the emergency behaviour:
   ![screen shot 2015-03-26 at 14 05 09](https://cloud.githubusercontent.com/assets/1153084/6847823/36acb9c4-d3c1-11e4-956b-dc3b255cfeb5.png)
3. In the emergency behaviour, Henry will drive to the nearest safety zone and then turn on "motor stop" and "free run", allowing it to be pushed around by people easily. It will also disable execution of tasks by calling the `/task_executor` to disable execution of tasks, so that it stays there. 
4. The service will have to be manually resumed by the admin team (remotely) after confirmation from the AAF team that it is safe to operate again.

comments on this sought from @denisehe @hawesie @mzillich @Jailander @cdondrup

**Comment by cdondrup** [comment]
Instead of asking people to tell the robot admin staff that they sent it away, could the script just send an email to Denise and us?
Rest looks good I think. Just have to make sure that really all tasks are interruptible.

**Comment by Jailander** [comment]
yes we can tag safe nodes and have a service for getting the closest "safe" node and navigate to it

**Comment by marc-hanheide** [comment]
Yes, the email feature would be good. How to do it? There was a service in strands_social?

**Comment by marc-hanheide** [comment]
And... anyone volunteering to implement the emergency behaviour?

**Comment by marc-hanheide** [comment]
I would actually prefer not only the executor to be set to false, but rather have topo_nav to take to and keep the robot in a safety zone, no matter what. E.g. by submitting the next safety zones as a goal every second ;-)

**Comment by Jailander** [comment]
Yes there is a tool called strands_emails  and yes sending the robot directly with top nav was my suggestion

**Comment by denisehe** [comment]
yes i think it would a good idea to email us and that we then take care of the robot!

**Comment by denisehe** [comment]
Aja @marc-hanheide anstatt roboter-admin team wäre STRANDS-Team der Akademie für Altersforschung einleuchtender! Damit auch jeder weiß, wer damit genau gemeint ist!

:-)
