### ISSUE TITLE
[aaf_walking_group] Fixing arrows indicating the direction

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#7]
This does not work very reliable at the moment. Also, 
- [ ] please use different types of arrows. The arrows on a traffic light might be a good idea. But the ones currently used look too much like buttons
- [ ] tidy up the web page the buttons are on, e.g. no background image.

**Comment by cdondrup** [comment]
Please make this as general as possible. Just having it run as an action server so it can be used by everyone. Also, adding the ability of moving the head left, right, and centre and potentially include 5V indicators.

**Comment by cdondrup** [comment]
@denisehe here is Linda with her shiny new indicators :)
![linda_indi](https://cloud.githubusercontent.com/assets/4293484/6779278/6dd32c56-d152-11e4-8ab1-50600aa5d2b9.jpg)
Ignore the Christmastree

**Comment by denisehe** [comment]
_ignoring accomplished_ 

coooooool! hahahahahahaha - looks a bit freaky but cool :-D
