### ISSUE TITLE
[info-terminal] new task action server replacing approach_person_of_interest

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#78]
- [x] the current [approach_person_of_interest](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/info_terminal/approach_person_of_interest) should be refactored to be based on [AbstractTaskServer](https://github.com/strands-project/strands_executive/blob/hydro-release/strands_executive_msgs/src/strands_executive_msgs/abstract_task_server.py), so that a factory service for tasks (`..._create`) is available. 
- [x]  [approach_person_of_interest](https://github.com/strands-project/aaf_deployment/tree/indigo-devel/info_terminal/approach_person_of_interest) needs to be modified so it doesn't use a `Pose` to turn towards, as we don't have waving detection. Instead, it should just run at the waypoint, make the head and PTU turn towards the screen, and enable [strands_gazing](https://github.com/strands-project/strands_hri/tree/hydro-devel/strands_gazing) rather than approaching a person

**Comment by cdondrup** [comment]
As we discussed, I didn't really refactor the old action server but created a new and simpler one.
