### ISSUE TITLE
[info_task]

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#83]
The display of the info_terminal will also be shown while the robot is navigation during the info tasks. To account for the possibility of interaction before reaching the designated node, we should also take the current robot_pose into account when publishing the feedback.

The info_task action server will subscribe to `/robot_pose` and publish that along with the times and page numbers in the custom message. Currently not used in fremen but interesting for post analysis or possible new features before deployment.

**Comment by marc-hanheide** [comment]
indeed!

**Comment by cdondrup** [comment]
this will done in the gui scripts so it publishes directly when something is clicked and where. @gestom will change that.
