### ISSUE TITLE
[bellbot_gui] missing build_depend for `bellbot_scheduler`

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#84]
```
CMake Error at /opt/ros/indigo/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a package configuration file provided by "bellbot_scheduler"
  with any of the following names:

    bellbot_schedulerConfig.cmake
    bellbot_scheduler-config.cmake

```

(from https://lcas.lincoln.ac.uk/jenkins/job/ros-indigo-bellbot-gui_binarydeb_trusty_amd64/14/console)

I suppose the bellbot_scheduler shouldn't be used anymore, right? Can somebody with more knowledge than me fix this, please? @jailander or @yianni?

**Comment by cdondrup** [comment]
Just to link it: https://github.com/strands-project/strands_hri/issues/103

**Comment by marc-hanheide** [comment]
@cdondrup is right as alw... most of the time. I'll close this one as duplicate.
