### ISSUE TITLE
swappiness and the robot performance issues

### ISSUE THREAD

**Issue by cdondrup** [strands-project/aaf_deployment#88]
We observed that with the current aaf system running, the robot becomes rather slow and unresponsive which of course has several unwanted side effects. We assume that this is due to the low amount of RAM and processes being swapped quite regularly. We will try to [reconfigure the "swappiness"](http://askubuntu.com/questions/103915/how-do-i-configure-swappiness) and see if this has an effect. If anyone has any experience with that, you are welcome to chip in your two cents.

**Comment by cdondrup** [comment]
Setting swappiness to `10` seems to be a fair assumption and prevents swapping if not necessary to prevent PC from freezing.. Will test further.

**Comment by lucasb-eyer** [comment]
.02$: Turning down swappiness is a good idea, but in my experience swapping usually happens because of one process leaking or otherwise going crazy. Given enough time, an easy way to detect that is either checking htop while swapping occurs (needs patience) or disabling swap altogether (`sudo swapoff -a`) for one session and look at which process crashes.

**Comment by cdondrup** [comment]
This was mainly an issue because of too many components running on the main PC with only 4GB RAM. With the new more distributed set-up (especially getting rid of the java bits) this is not as big an issue any more. Swapping would only occur when additional behaviour is launched, like the walking group or bellbot. The only problem with this is, that there is still enough RAM but the swappiness level is too high so it swaps too early. I didn't observe any memory leaks.

**Comment by cdondrup** [comment]
Worked fine for the last few weeks on Linda. Changed it on Werner to be 10 by default.

**Comment by cburbridge** [comment]
See discussion on g4s deployment gitter.. Roscpp memory leak and
odometry_mileage are the problem.

Worked fine for the last few weeks on Linda. Changed it on Werner to be 10
by default.

**Comment by cdondrup** [comment]
I'm not on the g4s chat. What was the consensus on how to fix it? Not running it?

**Comment by cdondrup** [comment]
But regardless of leaks, the memory is very limited on the main PC and setting the swappiness does help response time.
