### ISSUE TITLE
[info-terminal] display menu from google docs

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#89]
simply display this page: https://docs.google.com/document/d/10OG5Yad8r3FqHGB6zD06NtwWmpEI9NMexCVwNUQBWMI/pub?embedded=true
for the weekly menu.

**Comment by cburbridge** [comment]
![menu](https://cloud.githubusercontent.com/assets/259580/7076974/1dcbe78c-df05-11e4-9436-286cd68d8f23.png)

On my "menu" branch: https://github.com/cburbridge/aaf_deployment/tree/menu

If it is ok then open a PR, but it will include the events page changes and my other PR should be merged first..

**Comment by marc-hanheide** [comment]
Nice. Well you open a PR?
