### ISSUE TITLE
[info-terminal] write Menu for info terminal

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#90]
Denise, please see https://docs.google.com/document/d/10OG5Yad8r3FqHGB6zD06NtwWmpEI9NMexCVwNUQBWMI/edit?usp=sharing and edit the menu. Make sure it fits on one page, thanks.

**Comment by marc-hanheide** [comment]
You shall be using this interface to update the menu every week, if that's ok.

**Comment by denisehe** [comment]
so should it be updated per week or do we have a daily list?

**Comment by marc-hanheide** [comment]
your call, really. This page is yours. Put horse pictures on it :smirk: or the menu (make sure the horses don't look yummy, though). It is displayed on the robot "as is", so if you want to put a daily menu on, then you'd have to update it every day. Or if we have a weekly menu, then that is displayed.
