### ISSUE TITLE
video annotation with timestamps

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#93]
image topic in, overlay in the right bottom corner with rostime and human-readable datetime (in seconds).
Even add waypoint and current task, please

**Comment by marc-hanheide** [comment]
Can we make this component so it also uses @cdondrup s "censoring" node, e.g. blank the video when in no recording zones.

**Comment by Jailander** [comment]
No problem I'll liase with @cdondrup to make it that way

**Comment by cdondrup** [comment]
The example in the [readme](https://github.com/strands-project/strands_navigation/blob/indigo-devel/topological_logging_manager/README.md) should work for this already.

**Comment by marc-hanheide** [comment]
not exactly. I want the video to be black (or something else) rather than not being send. This is so we can have a continuous video without having to fiddle with many out of sync video files in the analysis later.

**Comment by cdondrup** [comment]
Yes, in the case of the node not publishing, which is only when it dies, this would lead to no video being saved. Maybe just using the bool topic in a separate callback would be better, yes.

**Comment by marc-hanheide** [comment]
If I understand the readme correctly, the node wouldn't publish anything when at censored areas. But we want it still to publish images, just black ones...

**Comment by cdondrup** [comment]
"Whenever the robot is at a node that is in the white list, the script publishes true, false otherwise." It only doesn't publish if it dies. this is meant as a security precaution. So if you have a synchronised callback, it will either publish true or false depending on if you are at a whitelist node or not, but if it dies it doesn't publish and therefore the callback is not called any more.

**Comment by marc-hanheide** [comment]
okok, convinced.

**Comment by cdondrup** [comment]
But I actually talked to @Jailander, he will use the timestamped bool but in a separate callback. If this is too old, he will switch to a blank image, assuming the node dies but still publishing to not interrupt the recording.

**Comment by marc-hanheide** [comment]
done, right?
