### ISSUE TITLE
[info-terminal] set priority of task in infremen

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#94]
... from a new param `task_priority` as soon as https://github.com/strands-project/strands_executive/tree/priorities is merged

**Comment by cdondrup** [comment]
Do we really need a parameter? This can be set in the gcal interface, right?

**Comment by marc-hanheide** [comment]
no, because infremen implements another _routine_ besides GCal...

**Comment by marc-hanheide** [comment]
yes, this was indeed an accident...

**Comment by cdondrup** [comment]
It's just because I linked this as closed in the PR. But my confusion is at an all time high, yes :D
