### ISSUE TITLE
[infremen] don't set execution to true

### ISSUE THREAD

**Issue by marc-hanheide** [strands-project/aaf_deployment#97]
see here:
https://github.com/strands-project/aaf_deployment/blob/indigo-devel/info_terminal/infremen/src/infremen.cpp#L551

you mustn't make this call, as another component is in control of changing the executors status.

**Comment by marc-hanheide** [comment]
@gestom did you do anything about this yet?

**Comment by marc-hanheide** [comment]
It's a bit urgent with us testing in Vienna, or shall I do it?

**Comment by gestom** [comment]
Currently being tested by jenkins

**Comment by gestom** [comment]
IMHO can be merged: https://github.com/strands-project/aaf_deployment/pull/117
